swagger: "2.0"
info:
  description: Cumulocity microservice REST API for FloPro Integration
  version: "0.1"
  title: Cumulocity sensor microservice
host: cotham.eu-latest.cumulocity.com
basePath: /service/sensor-microservice
schemes:
- https
securityDefinitions:
  auth:
    type: basic
security:
- auth: []
paths:
  /:
    get:
      tags:
      - Test tags
      summary: Receive a welcome message
      description: Get Welcome message from the service
      produces:
      - application/json
      parameters:
        - in: query
          name: dummy 
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/inline_response_200'
  /sim-measurements:
    post:
      tags:
      - Simulation
      summary: Post a simulated measurement
      description: Post a simulated measurement to the Cumulocity API
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Request containing details about the simulated measurement
        required: true
        schema:
          $ref: '#/definitions/SimMeasurement'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreatedMeasurement'
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/InvalidRequestError'

definitions:
  SimMeasurement:
    type: object
    required:
    - dateTime
    - deviceId
    - simJSON
    - type
    properties:
      jwt:
        type: string
        description: JWT Token
      deviceId:
        type: string
        description: Device that is posting the measurement
      dateTime:
        type: string
        description: Date of measurement
      type:
        type: string
        description: Type of measurement
      simJSON:
        type: string
        description: JSON-formatted string containing simulation data
  CreatedMeasurement:
    type: object
    properties:
      self:
        type: string
      time:
        type: string
      id:
        type: string
      source:
        $ref: '#/definitions/CreatedMeasurement_source'
      type:
        type: string
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
  InvalidRequestError:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/InvalidRequestError_errors'
  inline_response_200:
    type: object
    properties:
      message:
        type: string
  CreatedMeasurement_source:
    type: object
    properties:
      self:
        type: string
      id:
        type: string
    description: Device that posted the measurement
  InvalidRequestError_errors:
    type: object
    properties:
      value:
        type: integer
      msg:
        type: string
      param:
        type: string
      location:
        type: string
   