swagger: "2.0"
info:
  description: Cumulocity sensor microservice REST API for FloPro Integration
  version: "0.1"
  title: Cumulocity sensor microservice
host: cotham.eu-latest.cumulocity.com
basePath: /service/sensor-microservice
schemes:
- https
security:
- auth: []
paths:
  /simMeasurements:
    post:
      tags:
      - Measurements
      summary: Post a simulated sensor measurement
      description: Post a simulated sensor measurement to the Cumulocity API
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: formData
        description: Device that is posting the measurement
        required: true
        type: string
      - name: dateTime
        in: formData
        description: Date of measurement
        required: true
        type: string
      - name: type
        in: formData
        description: Type of measurement
        required: true
        type: string
      - name: simJSON
        in: formData
        description: JSON-formatted string containing simulation data
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreatedMeasurement'
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/InvalidRequestError'
  /deviceMeasurements:
    post:
      tags:
      - Measurements
      summary: Post a device sensor measurement
      description: Post a device sensor measurement to the Cumulocity API
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: formData
        description: Device that is posting the measurement
        required: true
        type: string
      - name: dateTime
        in: formData
        description: Date of measurement
        required: true
        type: string
      - name: type
        in: formData
        description: Type of measurement
        required: true
        type: string
      - name: sensorName
        in: formData
        description: Sensor that read the measurement
        required: true
        type: string
      - name: measurementData
        in: formData
        description: JSON-formatted string containing measurement data.
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreatedMeasurement'
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/InvalidRequestError'
  /devices:
    post:
      tags:
      - Devices
      summary: Register a device
      description: Add (or update) a device object within the Cumulocity API inventory
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: externalIdType
        in: formData
        description: Type of the device
        required: true
        type: string
      - name: externalId
        in: formData
        description: External ID of the device, should always be a Physical ID (serial number, IMEI...) 
        required: true
        type: string
      - name: deviceName
        in: formData
        description: Name of the device
        required: true
        type: string
      - name: deviceType
        in: formData
        description: Type of the device
        required: true
        type: string
      - name: deviceModel
        in: formData
        description: Model of the device
        required: true
        type: string
      - name: deviceSerialNumber
        in: formData
        description: Physical ID (serial number, IMEI...) of the device
        required: true
        type: string
      - name: deviceFirmwareVersion
        in: formData
        description: Firmware version of the device
        required: false
        type: string
      - name: deviceAlt
        in: formData
        description: Altitude of the device
        required: false
        type: number
      - name: deviceLng
        in: formData
        description: Longitude of the device
        required: false
        type: number
      - name: deviceLat
        in: formData
        description: Latitude of the device
        required: false
        type: number
      - name: deviceDateTime
        in: formData
        description: Date of creation/update
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ManagedObject'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ManagedObject'
        "409":
          description: Conflict
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/InvalidRequestError'
  /devices/{deviceId}:
    put:
      tags:
      - Devices
      summary: Update a device
      description: Update an existing device object within the Cumulocity API inventory
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: path
        description: ID of the device
        required: true
        type: integer
      - name: alt
        in: formData
        description: Altitude of the device
        required: false
        type: number
      - name: lng
        in: formData
        description: Longitude of the device
        required: false
        type: number
      - name: lat
        in: formData
        description: Latitude of the device
        required: false
        type: number
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/DeviceInfo'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/InvalidRequestError'
    get:
      tags:
      - Devices
      summary: Get a device
      description: Read info about an existing device object within the Cumulocity API inventory
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: path
        description: ID of the device
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/DeviceInfo'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
      - Devices
      summary: Remove a device
      description: Delete an existing device object from the Cumulocity API inventory
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: path
        description: ID of the device
        required: true
        type: integer
      - name: externalId
        in: query
        description: External ID of the device 
        required: false
        type: string
      - name: externalIdType
        in: query
        description: Type of external ID
        required: false
        type: string
      responses:
        "204":
          description: No content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
  /devices/{deviceId}/events:
    post:
      tags:
      - Events
      summary: Post a new device event
      description: Add a new event (e.g. position update) for a device object within the Cumulocity API inventory
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: path
        description: ID of the device
        required: true
        type: integer
      - name: cTime
        in: formData
        description: Time of the event
        required: true
        type: string
      - name: cType
        in: formData
        description: Type of the event
        required: true
        type: string
      - name: cText
        in: formData
        description: Description of the event
        required: true
        type: string
      - name: alt
        in: formData
        description: Altitude of the device
        required: false
        type: number
      - name: lng
        in: formData
        description: Longitude of the device
        required: false
        type: number
      - name: lat
        in: formData
        description: Latitude of the device
        required: false
        type: number
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreatedEvent'
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/InvalidRequestError'
    get:
      tags:
      - Events
      summary: Get events for a device
      description: Get all the events posted by an existing device object within the Cumulocity API inventory
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: path
        description: ID of the device
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/DeviceEvents'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
  /environment:
    get:
      tags:
      - Extra
      summary: Get environment variables
      description: Read values of the environment variables used for authentication on the Cumulocity API
      produces:
      - application/json
      responses:
        "200":
          description: OK
    post:
      tags:
      - Extra
      summary: Write/Modify environment variables
      description: (TEST - BE CAREFUL) Assign new values to the environment variables used for authentication on the Cumulocity API
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: tenant
        in: formData
        description: Tenant
        required: true
        type: string
      - name: user
        in: formData
        description: Username
        required: true
        type: string
      - name: password
        in: formData
        description: Password
        required: true
        type: string
      responses:
        "200":
          description: OK
  /instances:
    get:
      tags:
      - Extra
      summary: Get server instances
      description: Get server instances
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Instances'
securityDefinitions:
  auth:
    type: basic
definitions:
  ManagedObject:
    type: object
    properties:
      managedObject:
        $ref: '#/definitions/ManagedObject_source'
      externalId:
        type: string
      self:
        type: string
      type:
        type: string
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
  CreatedMeasurement:
    type: object
    properties:
      self:
        type: string
      time:
        type: string
      id:
        type: string
      source:
        $ref: '#/definitions/CreatedMeasurement_source'
      type:
        type: string
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
  InvalidRequestError:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/InvalidRequestError_errors'
  CreatedEvent:
    type: object
    properties:
      creationTime:
        type: string
      source:
        $ref: '#/definitions/CreatedEvent_source'
      type:
        type: string
      self:
        type: string
      time:
        type: string
      text:
        type: string
      id:
        type: string
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
  DeviceInfo:
    type: object
    properties:
      additionParents:
        $ref: '#/definitions/ObjectReferences'
      owner:
        type: string
      childDevices:
        $ref: '#/definitions/ObjectReferences'
      childAssets:
        $ref: '#/definitions/ObjectReferences'
      creationTime:
        type: string
      type:
        type: string
      lastUpdated:
        type: string
      childAdditions:
        $ref: '#/definitions/ObjectReferences'
      name:
        type: string
      assetParents:
        $ref: '#/definitions/ObjectReferences'
      deviceParents:
        $ref: '#/definitions/ObjectReferences'
      self:
        type: string
      id:
        type: string
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
  ErrorResponse:
    type: object
    properties: 
      error:
        type: string
      message:
        type: string
      info:
        type: string
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
  DeviceEvents:
    type: object
    properties:
      next:
        type: string
      self:
        type: string
      events:
        type: array
        items:
          $ref: '#/definitions/Event'
      statistics:
        $ref: '#/definitions/Statistics'
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
  Instances:
    type: object
    properties:
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
      instances:
        type: array
        items:
          $ref: '#/definitions/Instance'
  Event:
    type: object
    properties:
      creationTime:
        type: string
      source:
        $ref: '#/definitions/CreatedEvent_source'
      type:
        type: string
      self:
        type: string
      time:
        type: string
      text:
        type: string
      id:
        type: string
  ObjectReferences:
    type: object
    properties:
      self:
        type: string
      references:
        type: array
        items:
          type: string
  CreatedEvent_source:
    type: object
    properties:
      name:
        type: string
      self:
        type: string
      id:
        type: string
    description: Device that posted the event
  CreatedMeasurement_source:
    type: object
    properties:
      self:
        type: string
      id:
        type: string
    description: Device that posted the measurement
  ManagedObject_source:
    type: object
    properties:
      self:
        type: string
      id:
        type: string
    description: Device that was created/updated
  InvalidRequestError_errors:
    type: object
    properties:
      value:
        type: integer
      msg:
        type: string
      param:
        type: string
      location:
        type: string
  Instance:
    type: object
    properties:
      description:
        type: string
  Statistics:
    type: object
    properties:
      currentPage:
        type: integer
      pageSize:
        type: integer