swagger: '2.0'
info:
  version: "1.0"
  title: 'Cumulocity Sensor API'
  description: 'Cumulocity Sensor API - Kumulos RPC API , use APIkey/Secret Key as Credentials'


host: api.kumulos.com
basePath: /b2.2/58f128a7-3f4e-449b-81b7-64def90bfda7

schemes:
  - https
securityDefinitions:
  basicAuth:
    type: basic

# To apply Basic auth to the whole API:
security:
  - basicAuth: []

paths:

  /cumulocity_Get_Events.json/:
    post:
      description: Get Events 
      summary: Get Events 
      tags:
        - Event
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: params[jwt]
          type: string
          description: jwt
          required: true
        - in: formData
          name: params[deviceId]
          type: string
          description: deviceId
          required: true
       

      responses:
        200:
          description: Return a standard response format for JSONRPC - if responseCode in this response is a success (1). Any other response code is an error.
          schema:
            type: object
            properties:
              responseCode:
                type: integer
              responseMessage:
                type: string
              payload:
                type: object
                properties:
                  events: 
                    type: array
                    items:
                      type: object
                      properties: 
                        creationTime:
                          type: string
                        source:
                          type: object
                          properties: 
                            name: 
                              type: string
                            id: 
                              type: string
                        type: 
                          type: string
                        time:
                          type: string
                        id: 
                          type: string
                        c8y_Position:
                          type: object
                          properties:
                            alt:
                              type: string
                            lng:
                              type: string 
                            lat:
                              type: string

                  isError:
                    type: string
                  StatusCode:
                    type: string
                  error:
                    type: string
                  info:
                    type: string
                  message:
                    type: string
              sessionToken:
                type: string
              requestedMethod:
                type: string
              requestedFormat:
                type: string
              timestamp:
                type: string
                format: date-time
              requestReceivedTime:
                type: string
                format: date-time
              maxAllowedRequestTime:
                type: integer
              requestProcessingTime:
                type: number
                format: double

        default:
          description: Failed Server Response

  /cumulocity_Update_Device.json/:
    post:
      description: Update Device
      summary: Update Device
      tags:
        - Inventory
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: params[jwt]
          type: string
          description: jwt
          required: true
        - in: formData
          name: params[deviceId]
          type: string
          description: deviceId
          required: true
        - in: formData
          name: params[alt]
          type: string
          description: alt
        - in: formData
          name: params[lng]
          type: string
          description: lng
        - in: formData
          name: params[lat]
          type: string
          description: lat

      responses:
        200:
          description: Return a standard response format for JSONRPC - if responseCode in this response is a success (1). Any other response code is an error.
          schema:
            type: object
            properties:
              responseCode:
                type: integer
              responseMessage:
                type: string
              payload:
                type: object
                properties:
                  owner: 
                    type: string
                  creationTime: 
                    type: string
                  lastUpdated: 
                    type: string
                  type: 
                    type: string
                  name: 
                    type: string
                  id: 
                    type: string
                  c8y_Hardware:
                    type: object
                    properties:
                      model:
                        type: string
                      serialNumber:
                        type: string 
                  c8y_Mobile:
                    type: object
                    properties:
                      imei:
                        type: string
                      cellId:
                        type: string 
                      iccid:
                        type: string 
                  c8y_Firmware:
                    type: object
                    properties:
                      version:
                        type: string
                  c8y_Position:
                    type: object
                    properties:
                      alt:
                        type: string
                      lng:
                        type: string 
                      lat:
                        type: string
                  isError:
                    type: string
                  StatusCode:
                    type: string
                  error:
                    type: string
                  info:
                    type: string
                  message:
                    type: string
              sessionToken:
                type: string
              requestedMethod:
                type: string
              requestedFormat:
                type: string
              timestamp:
                type: string
                format: date-time
              requestReceivedTime:
                type: string
                format: date-time
              maxAllowedRequestTime:
                type: integer
              requestProcessingTime:
                type: number
                format: double

        default:
          description: Failed Server Response
  
  /cumulocity_Get_Device.json/:
    post:
      description: Get Device
      summary: Get Device
      tags:
        - Inventory
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: params[jwt]
          type: string
          description: jwt
          required: true
        - in: formData
          name: params[deviceId]
          type: string
          description: deviceId
          required: true
        
        

      responses:
        200:
          description: Return a standard response format for JSONRPC - if responseCode in this response is a success (1). Any other response code is an error.
          schema:
            type: object
            properties:
              responseCode:
                type: integer
              responseMessage:
                type: string
              payload:
                type: object
                properties:
                  owner: 
                    type: string
                  creationTime: 
                    type: string
                  lastUpdated: 
                    type: string
                  type: 
                    type: string
                  name: 
                    type: string
                  id: 
                    type: string
                  c8y_Hardware:
                    type: object
                    properties:
                      model:
                        type: string
                      serialNumber:
                        type: string 
                  c8y_Mobile:
                    type: object
                    properties:
                      imei:
                        type: string
                      cellId:
                        type: string 
                      iccid:
                        type: string 
                  c8y_Firmware:
                    type: object
                    properties:
                      version:
                        type: string
                  c8y_Position:
                    type: object
                    properties:
                      alt:
                        type: string
                      lng:
                        type: string 
                      lat:
                        type: string
                  isError:
                    type: string
                  StatusCode:
                    type: string
                  error:
                    type: string
                  info:
                    type: string
                  message:
                    type: string
              sessionToken:
                type: string
              requestedMethod:
                type: string
              requestedFormat:
                type: string
              timestamp:
                type: string
                format: date-time
              requestReceivedTime:
                type: string
                format: date-time
              maxAllowedRequestTime:
                type: integer
              requestProcessingTime:
                type: number
                format: double

        default:
          description: Failed Server Response

  /cumulocity_RegisterDevice.json/:
    post:
      description: Register/Create Device
      summary: Register/Create device 
      tags:
        - User
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: params[jwt]
          type: string
          description: jwt
          required: true
        - in: formData
          name: params[externalIdType]
          type: string
          description: externalIdType
          required: true
        - in: formData
          name: params[externalId]
          type: string
          description: externalId
          required: true
        - in: formData
          name: params[deviceName]
          type: string
          description: deviceName
          required: true
        - in: formData
          name: params[deviceType]
          type: string
          description: deviceType
          required: true
        - in: formData
          name: params[deviceModel]
          type: string
          description: deviceModel
          required: true
        - in: formData
          name: params[deviceSerialNumber]
          type: string
          description: deviceSerialNumber
          required: true
        - in: formData
          name: params[deviceFirmwareVersion]
          type: string
          description: deviceFirmwareVersion
          required: true
        - in: formData
          name: params[deviceAlt]
          type: string
          description: deviceAlt
          required: true
        - in: formData
          name: params[deviceLng]
          type: string
          description: deviceLng
          required: true
        - in: formData
          name: params[deviceLat]
          type: string
          description: deviceLat
          required: true
        - in: formData
          name: params[deviceDateTime]
          type: string
          description: deviceDateTime
          required: true
        

      responses:
        200:
          description: Return a standard response format for JSONRPC - if responseCode in this response is a success (1). Any other response code is an error.
          schema:
            type: object
            properties:
              responseCode:
                type: integer
              responseMessage:
                type: string
              payload:
                type: object
                properties:
                  externalId:
                    type: string
                  managedObject:
                    type: object
                    properties:
                      id:
                        type: string
                      self:
                        type: string
                  self:
                    type: string
                  type:
                    type: string
                  isError:
                    type: string
                  StatusCode:
                    type: string
                  error:
                    type: string
                  info:
                    type: string
                  message:
                    type: string
              sessionToken:
                type: string
              requestedMethod:
                type: string
              requestedFormat:
                type: string
              timestamp:
                type: string
                format: date-time
              requestReceivedTime:
                type: string
                format: date-time
              maxAllowedRequestTime:
                type: integer
              requestProcessingTime:
                type: number
                format: double

        default:
          description: Failed Server Response

  /cumulocity_Login.json/:
    post:
      description: Login
      summary: Login
      tags:
        - User
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: params[email]
          type: string
          description: email
          required: true
        - in: formData
          name: params[password]
          type: string
          description: password
          required: true
        - in: formData
          name: params[tenant]
          type: string
          description: tenant
          required: true
        - in: formData
          name: params[instance]
          type: string
          description: instance
          required: true
        - in: formData
          name: params[qrCodeData]
          type: string
          description: qrCodeData
          required: true
        

      responses:
        200:
          description: Return a standard response format for JSONRPC - if responseCode in this response is a success (1). Any other response code is an error.
          schema:
            type: object
            properties:
              responseCode:
                type: integer
              responseMessage:
                type: string
              payload:
                type: object
                properties:
                  lastName:
                    type: string
                  userName:
                    type: string
                  firstName:
                    type: string
                  id:
                    type: string
                  token:
                    type: string
                  expiresAt:
                    type: string
                  isError:
                    type: string
                  StatusCode:
                    type: string
                  error:
                    type: string
                  info:
                    type: string
                  message:
                    type: string
              sessionToken:
                type: string
              requestedMethod:
                type: string
              requestedFormat:
                type: string
              timestamp:
                type: string
                format: date-time
              requestReceivedTime:
                type: string
                format: date-time
              maxAllowedRequestTime:
                type: integer
              requestProcessingTime:
                type: number
                format: double

        default:
          description: Failed Server Response

  /cumulocity_PostEvent.json/:
    post:
      description: Create new event
      summary: Create new event
      tags:
        - Event
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: params[jwt]
          type: string
          description: jwt
          required: true
        - in: formData
          name: params[cText]
          type: string
          description: cText
          required: true
        - in: formData
          name: params[cTime]
          type: string
          description: cTime
          required: true
        - in: formData
          name: params[cType]
          type: string
          description: cType
          required: true
        - in: formData
          name: params[sourceId]
          type: string
          description: sourceId
          required: true
        - in: formData
          name: params[alt]
          type: string
          description: alt
          required: true
        - in: formData
          name: params[lng]
          type: string
          description: lng
          required: true
        - in: formData
          name: params[lat]
          type: string
          description: lat
          required: true

      responses:
        200:
          description: Return a standard response format for JSONRPC - if responseCode in this response is a success (1). Any other response code is an error.
          schema:
            type: object
            properties:
              responseCode:
                type: integer
              responseMessage:
                type: string
              payload:
                type: string
              sessionToken:
                type: string
              requestedMethod:
                type: string
              requestedFormat:
                type: string
              timestamp:
                type: string
                format: date-time
              requestReceivedTime:
                type: string
                format: date-time
              maxAllowedRequestTime:
                type: integer
              requestProcessingTime:
                type: number
                format: double

        default:
          description: Failed Server Response