swagger: "2.0"
info:
  description: Cumulocity sensor microservice REST API for FloPro Integration
  version: "0.1"
  title: Cumulocity sensor microservice
host: cotham.eu-latest.cumulocity.com
basePath: /service/sensor-microservice
schemes:
- https
security:
- auth: []
paths:
  /sim-measurements:
    post:
      tags:
      - Measurement
      summary: Post a simulated sensor measurement
      description: Post a simulated sensor measurement to the Cumulocity API
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: formData
        description: Device that is posting the measurement
        required: true
        type: string
      - name: dateTime
        in: formData
        description: Date of measurement
        required: true
        type: string
      - name: type
        in: formData
        description: Type of measurement
        required: true
        type: string
      - name: simJSON
        in: formData
        description: JSON-formatted string containing simulation data
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreatedMeasurement'
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/InvalidRequestError'
  /device-measurements:
    post:
      tags:
      - Measurement
      summary: Post a device sensor measurement
      description: Post a device sensor measurement to the Cumulocity API
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: formData
        description: Device that is posting the measurement
        required: true
        type: string
      - name: dateTime
        in: formData
        description: Date of measurement
        required: true
        type: string
      - name: type
        in: formData
        description: Type of measurement
        required: true
        type: string
      - name: sensorName
        in: formData
        description: Sensor that read the measurement
        required: true
        type: string
      - name: measurementData
        in: formData
        description: JSON-formatted string containing measurement data.
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreatedMeasurement'
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/InvalidRequestError'
  /devices:
    post:
      tags:
      - Device
      summary: Register a device
      description: Add (or update) a device object within the Cumulocity API inventory
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: externalIdType
        in: formData
        description: Type of the device
        required: true
        type: string
      - name: externalId
        in: formData
        description: External ID of the device, should always be a Physical ID (serial number, IMEI...) 
        required: true
        type: string
      - name: deviceName
        in: formData
        description: Name of the device
        required: true
        type: string
      - name: deviceType
        in: formData
        description: Type of the device
        required: true
        type: string
      - name: deviceModel
        in: formData
        description: Model of the device
        required: true
        type: string
      - name: deviceSerialNumber
        in: formData
        description: Physical ID (serial number, IMEI...) of the device
        required: true
        type: string
      - name: deviceFirmwareVersion
        in: formData
        description: Firmware version of the device
        required: true
        type: string
      - name: deviceAlt
        in: formData
        description: Altitude of the device
        required: false
        type: number
      - name: deviceLng
        in: formData
        description: Longitude of the device
        required: true
        type: number
      - name: deviceLat
        in: formData
        description: Latitude of the device
        required: true
        type: number
      - name: deviceDateTime
        in: formData
        description: Date of creation/update
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ManagedObject'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ManagedObject'
        "409":
          description: Conflict
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/InvalidRequestError'
securityDefinitions:
  auth:
    type: basic
definitions:
  ManagedObject:
    type: object
    properties:
      managedObject:
        $ref: '#/definitions/ManagedObject_source'
      externalId:
        type: string
      self:
        type: string
      type:
        type: string
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
  CreatedMeasurement:
    type: object
    properties:
      self:
        type: string
      time:
        type: string
      id:
        type: string
      source:
        $ref: '#/definitions/CreatedMeasurement_source'
      type:
        type: string
      statusCode:
        type: integer
      statusText:
        type: string
      isError:
        type: boolean
  InvalidRequestError:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/InvalidRequestError_errors'
  CreatedMeasurement_source:
    type: object
    properties:
      self:
        type: string
      id:
        type: string
    description: Device that posted the measurement
  ManagedObject_source:
    type: object
    properties:
      self:
        type: string
      id:
        type: string
    description: Device that was created/updated
  InvalidRequestError_errors:
    type: object
    properties:
      value:
        type: integer
      msg:
        type: string
      param:
        type: string
      location:
        type: string