swagger: "2.0"
info:
  description: Cumulocity REST API for FloPro Integration
  version: "0.1"
  title: Cumulocity REST API
host: cotham.eu-latest.cumulocity.com
basePath: /
schemes:
- https
security:
- auth: []
paths:
  /alarm/alarms:
    post:
      tags:
      - Alarms
      summary: Create a new Alarm
      description: http://cumulocity.com/guides/reference/alarms/
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: The Alarm to create
        schema:
          type: object
          properties:
            type:
              type: string
            time:
              type: string
            text:
              type: string
            status:
              type: string
            severity:
              type: string
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Alarm'
        default:
          description: Other Error
          schema:
            $ref: '#/definitions/GenericError'
securityDefinitions:
  auth:
    type: basic
definitions:
  GenericError:
    type: object
    properties:
      error:
        type: string
      info:
        type: string
      message:
        type: string
  AlarmAPI:
    type: object
    properties:
      self:
        type: string
      alarms:
        type: string
      alarmsForStatus:
        type: string
      alarmsForSource:
        type: string
      alarmsForSourceAndStatus:
        type: string
      alarmsForTime:
        type: string
      alarmsForStatusAndTime:
        type: string
      alarmsForSourceAndTime:
        type: string
      alarmsForSourceAndStatusAndTime:
        type: string
      alarmsForSourceWithAssetsAndWithDevices:
        type: string
      alarmsForSeverity:
        type: string
      alarmsForResolved:
        type: string
  Alarm:
    type: object
    properties:
      self:
        type: integer
      id:
        type: string
      time:
        type: string
      type:
        type: string
      creationTime:
        type: integer
      text:
        type: string
      status:
        type: string
      severity:
        type: string
      count:
        type: integer
      firstOccurrenceTime:
        type: string
      source:
        $ref: '#/definitions/Alarm_source'
  AlarmCollection:
    type: object
    properties:
      next:
        type: string
      prev:
        type: string
      self:
        type: integer
      statistics:
        $ref: '#/definitions/PagingStatistics'
      alarms:
        type: array
        items:
          $ref: '#/definitions/Alarm'
  Alarm_source:
    type: object
    properties:
      self:
        type: string
      id:
        type: integer
  PagingStatistics:
    type: object
    properties:
      totalPages:
        type: integer
      currentPage:
        type: integer
      pageSize:
        type: integer