swagger: "2.0"
info:
  description: Cumulocity REST API for FloPro Integration. This API has been converted from the official Cumulocity Postman Collection.
    https://cumulocity.com/guides/reference/rest-implementation/
  version: "0.1"
  title: Cumulocity REST API
host: cotham.eu-latest.cumulocity.com
basePath: /
schemes:
- https
security:
- auth: []
paths:
  /alarm:
    get:
      tags:
      - Alarms
      summary: Get the AlarmAPI resource
      description: >-
        #### For a detailed description of the API please check out the [Alarm
        Reference Guide](http://cumulocity.com/guides/reference/alarms/)
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AlarmAPI'
        default:
          description: Other Error
          schema:
            $ref: '#/definitions/GenericError'
  /alarm/alarms:
    get:
      tags:
      - Alarms
      summary: Get an alarm collection
      description: >-
        #### For a detailed description of the API please check out the [Alarm
        Reference Guide](http://cumulocity.com/guides/reference/alarms/)
      produces:
      - application/json
      parameters:
        - in: query
          name: pageSize
          description: Default 5, Max 2000
          type: integer
        - in: query
          name: currentPage
          type: integer
        - in: query
          name: withTotalPages
          type: boolean
        - in: query
          name: dateFrom
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: dateTo
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: status
          description: status={status}
          type: string
        - in: query
          name: resolved
          description: resolved={resolved}
          type: string
        - in: query
          name: severity
          description: severity={severity}
          type: string
        - in: query
          name: source
          description: source={source}
          type: string
        - in: query
          name: withAssets
          description: withAssets={withAssets}
          type: string
        - in: query
          name: withDevices
          description: withDevices={withDevices}
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AlarmCollection'
        default:
          description: Other Error
          schema:
            $ref: '#/definitions/GenericError'
    post:
      tags:
      - Alarms
      summary: Create a new Alarm
      description: >-
        #### For a detailed description of the API please check out the [Alarm
        Reference Guide](http://cumulocity.com/guides/reference/alarms/)
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Alarm
        description: The Alarm to create
        required: true
        schema:
          type: object
          properties:
            type:
              type: string
            time:
              type: string
            text:
              type: string
            source:
                type: object
                properties:
                  self:
                    type: string
                  id:
                    type: string
            status:
              type: string
            severity:
              type: string
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Alarm'
        default:
          description: Other Error
          schema:
            $ref: '#/definitions/GenericError'
    put:
      tags:
      - Alarms
      summary: Bulk update of alarm collection
      description: >-
        #### For a detailed description of the API please check out the [Alarm
        Reference Guide](http://cumulocity.com/guides/reference/alarms/)
        
        The PUT method allows for updating alarms collections. Currently only the status of alarms can be changed.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: status
        description: Comma separated alarm statuses, for example ACTIVE,CLEARED.
        type: string
      - in: query
        name: source
        description: Source device id.
        type: string
      - in: query
        name: resolved
        description: When set to true only resolved alarms will be updated (the one with status CLEARED), false means alarms with status ACTIVE or ACKNOWLEDGED.
        type: boolean
      - in: query
        name: severity
        description: Alarm severity, for example MINOR.
        type: string
      - in: query
        name: dateFrom
        description: Start date or date and time of alarm occurrence. Example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
        type: string
      - in: query
        name: dateTo
        description: End date or date and time of alarm occurrence. Example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
        type: string
      - in: body
        name: Status
        description: The status to update
        required: true
        schema:
          type: object
          properties:
            status:
              type: string
      responses:
        200:
          description: Updated
        202:
          description: Process continuing in background
        default:
          description: Other Error
          schema:
            $ref: '#/definitions/GenericError'
    delete:
      tags:
      - Alarms
      summary: Delete an alarm collection
      description: >-
        #### For a detailed description of the API please check out the [Alarm
        Reference Guide](http://cumulocity.com/guides/reference/alarms/)
        
        Important: Note that it is possible to call this endpoint without providing any parameter - it will result in deleting all alarms and it is not recommended.
      produces:
      - application/json
      parameters:
        - in: query
          name: status
          description: Comma separated alarm statuses, for example ACTIVE,CLEARED.
          type: string
        - in: query
          name: source
          description: Source device id.
          type: string
        - in: query
          name: withSourceAssets
          description: When set to true also alarms for related source assets will be removed. When this parameter is provided also source must be defined.
          type: boolean
        - in: query
          name: withSourceDevices
          description: When set to true also alarms for related source devices will be removed. When this parameter is provided also source must be defined.
          type: boolean
        - in: query
          name: resolved
          description: When set to true only resolved alarms will be removed (the one with status CLEARED), false means alarms with status ACTIVE or ACKNOWLEDGED.
          type: boolean
        - in: query
          name: severity
          description: Alarm severity, for example MINOR.
          type: string
        - in: query
          name: dateFrom
          description: Start date or date and time of alarm occurrence. Example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: dateTo
          description: End date or date and time of alarm occurrence. Example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: type
          description: Alarm type.
          type: string
      responses:
        204:
          description: No content
        default:
          description: Other Error
          schema:
            $ref: '#/definitions/GenericError'
  /alarm/alarms/{alarmId}:
    get:
      tags:
      - Alarms
      summary: Get an Alarm 
      description: >-
        #### For a detailed description of the API please check out the [Alarm
        Reference Guide](http://cumulocity.com/guides/reference/alarms/)
      produces:
      - application/json
      parameters:
        - in: path
          name: alarmId
          description: Alarm id.
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Alarm'
        default:
          description: Other Error
          schema:
            $ref: '#/definitions/GenericError'
    put:
      tags:
      - Alarms
      summary: Update an Alarm
      description: >-
        #### For a detailed description of the API please check out the [Alarm
        Reference Guide](http://cumulocity.com/guides/reference/alarms/)
        
        Only text, status, severity and custom properties can be modified. Non-modifiable fields will be ignored when provided in request.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: alarmId
        description: Alarm id.
        required: true
        type: string
      - in: body
        name: Alarm
        description: The alarm properties to update
        required: true
        schema:
          type: object
          properties:
            text:
              type: string
            status:
              type: string
            severity:
              type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Alarm'
        default:
          description: Other Error
          schema:
            $ref: '#/definitions/GenericError'
securityDefinitions:
  auth:
    type: basic
definitions:
  GenericError:
    type: object
    properties:
      error:
        type: string
      info:
        type: string
      message:
        type: string
  AlarmAPI:
    type: object
    properties:
      self:
        type: string
      alarms:
        type: string
      alarmsForStatus:
        type: string
      alarmsForSource:
        type: string
      alarmsForSourceAndStatus:
        type: string
      alarmsForTime:
        type: string
      alarmsForStatusAndTime:
        type: string
      alarmsForSourceAndTime:
        type: string
      alarmsForSourceAndStatusAndTime:
        type: string
      alarmsForSourceWithAssetsAndWithDevices:
        type: string
      alarmsForSeverity:
        type: string
      alarmsForResolved:
        type: string
  Alarm:
    type: object
    properties:
      self:
        type: integer
      id:
        type: string
      time:
        type: string
      type:
        type: string
      creationTime:
        type: integer
      text:
        type: string
      status:
        type: string
      severity:
        type: string
      count:
        type: integer
      firstOccurrenceTime:
        type: string
      source:
        $ref: '#/definitions/ManagedObject'
  AlarmCollection:
    type: object
    properties:
      next:
        type: string
      prev:
        type: string
      self:
        type: integer
      statistics:
        $ref: '#/definitions/PagingStatistics'
      alarms:
        type: array
        items:
          $ref: '#/definitions/Alarm'
  ManagedObject:
    type: object
    properties:
      self:
        type: string
      id:
        type: integer
  PagingStatistics:
    type: object
    properties:
      totalPages:
        type: integer
      currentPage:
        type: integer
      pageSize:
        type: integer