swagger: '2.0'
info:
  version: '1.0'
  title: Cumulocity  API
  description: https://cumulocity.com/guides/microservice-sdk/rest/

host: cotham.eu-latest.cumulocity.com
basePath: 

schemes:
  - https

securityDefinitions:
  auth:
    type: basic
security:
  - auth: []

paths:
  
  /tenant/loginOptions:
    get:
      description: Get Tenant Login details
      summary: Get Tenant Login details
      tags:
        - Tenant
      produces:
        - application/json
      parameters:
        - in: header
          name: Host
          type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              loginOptions:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: string
                    visibleOnLoginPage:
                      type: integer
                    buttonName:
                      type: string
                    initRequest:
                      type: string

        default:
          description: server error


          
  
  /user/currentUser:
    get:
      description: Get Current user details
      summary: Get current user information
      tags:
        - User
      produces:
        - application/json
      parameters:
        - in: query
          name: dummy
          type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lastName:
                type: string
              userName:
                type: string
              firstName:
                type: string
        401:
          description: Unauthorised
        
        default:
          description: server error
  
  