swagger: "2.0"
info:
  description: Cumulocity REST API for FloPro Integration. This API has been converted from the official Cumulocity Postman Collection.
    https://cumulocity.com/guides/reference/rest-implementation/
  version: "0.1"
  title: Cumulocity REST API
host: cotham.eu-latest.cumulocity.com

schemes:
- https

securityDefinitions:
  auth:
    type: basic

security:
- auth: []

paths:
 
  /alarm/alarms:
    get:
      tags:
      - Alarms
      summary: Get an alarm collection
      description: Get an alarm collection
      produces:
      - application/json
      parameters:
        - in: query
          name: pageSize
          description: Default 5, Max 2000
          type: integer
        - in: query
          name: currentPage
          type: integer
        - in: query
          name: withTotalPages
          type: boolean
        - in: query
          name: dateFrom
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: dateTo
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: status
          description: status={status}
          type: string
        - in: query
          name: resolved
          description: resolved={resolved}
          type: string
        - in: query
          name: severity
          description: severity={severity}
          type: string
        - in: query
          name: source
          description: source={source}
          type: string
        - in: query
          name: withAssets
          description: withAssets={withAssets}
          type: string
        - in: query
          name: withDevices
          description: withDevices={withDevices}
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              next:
                type: string
              prev:
                type: string
              self:
                type: integer
              statistics:
                type: object
                properties:
                  totalPages:
                    type: integer
                  currentPage:
                    type: integer
                  pageSize:
                    type: integer
              alarms:
                type: array
                items:
                  type: object
                  properties:
                    self:
                      type: integer
                    id:
                      type: string
                    time:
                      type: string
                    type:
                      type: string
                    creationTime:
                      type: integer
                    text:
                      type: string
                    status:
                      type: string
                    severity:
                      type: string
                    count:
                      type: integer
                    firstOccurrenceTime:
                      type: string
                    source:
                      type: object
                      properties:
                        self:
                          type: string
                        id:
                          type: string
                        name:
                          type: string
                        type:
                          type: string
        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string
