swagger: '2.0'
info:
  version: '1.0'
  title: Cumulocity  API
  description: https://cumulocity.com/guides/microservice-sdk/rest/

host: cotham.eu-latest.cumulocity.com
basePath: 

schemes:
  - https

securityDefinitions:
  auth:
    type: basic
security:
  - auth: []

paths:
  
  /inventory/managedObjects:
    get:
      description: Get Inventory Items
      summary: Get Inventory Items
      tags:
        - Tenant
      produces:
        - application/json
      parameters:
        - in: query
          name: pageSize
          type: integer
        - in: query
          name: query
          type: string

      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              loginOptions:
                type: array
                items:
                  type: object
                  properties:
                    next: 
                      type: string
                    self:
                      type: integer
                    statistics:
                      type: object
                      properties:
                        totalPages:
                          type: integer
                        currentPage:
                          type: integer
                        pageSize:
                          type: integer
                    managedObjects:
                      type: array
                      items:
                        type: object
                        properties:
                          owner: 
                            type: string
                          creationTime: 
                            type: string
                          lastUpdated: 
                            type: string
                          type: 
                            type: string
                          name: 
                            type: string
                          id: 
                            type: string
                          c8y_Position: 
                            type: object
                            properties:
                              lng:
                                type: string
                              lat:
                                type: string
                              alt:
                                type: string
                          c8y_Hardware: 
                            type: object
                            properties:
                              serialNumber:
                                type: string
                              model:
                                type: string
                          

                    

        default:
          description: server error
  
    post:
      description: Add Inventory Items
      summary: Create device with temperature measurement support
      tags:
        - Inventory

      produces:
        - application/json
      parameters:
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            type: object
            properties:
              name:
                type: string
              type: 
                type: string
              c8y_IsDevice:
                type: string
              c8y_SupportedMeasurements:
                type: string
              c8y_Hardware:
                type: string 
            
      responses:
        '201':
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              lastUpdated:
                type: string
              name:
                type: string
              owner:
                type: string
              type: 
                type: string
              

        default:
          description: server error


  /tenant/loginOptions:
    get:
      description: Get Tenant Login details
      summary: Get Tenant Login details
      tags:
        - Inventory
      produces:
        - application/json
      parameters:
        - in: header
          name: Host
          type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              loginOptions:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: string
                    visibleOnLoginPage:
                      type: integer
                    buttonName:
                      type: string
                    initRequest:
                      type: string

        default:
          description: server error

  
          
  
  /user/currentUser:
    get:
      description: Get Current user details
      summary: Get current user information
      tags:
        - User
      produces:
        - application/json
      parameters:
        - in: query
          name: dummy
          type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lastName:
                type: string
              userName:
                type: string
              firstName:
                type: string
        401:
          description: Unauthorised
        
        default:
          description: server error
  
  