swagger: '2.0'
info:
  version: '1.0'
  title: Cumulocity  API
  description: https://cumulocity.com/guides/microservice-sdk/rest/

host: cotham.eu-latest.cumulocity.com
basePath: 

schemes:
  - https

securityDefinitions:
  auth:
    type: basic
security:
  - auth: []

paths:
  
  /identity/globalIds/{deviceId}/externalIds:
    get:
      description: Get all externalIds registered for a managedObject
      summary: Get all externalIds registered for a managedObject
      tags:
        - Identity
      produces:
        - application/json
      parameters:
        - name: deviceId
          in: path
          required: true
          type: string
          description: Unique external ID
      responses:
        200:
          description: Found Device
          schema:
            type: object
            properties:
              externalId:
                type: string
              managedObject:
                type: object
                properties:
                  id:
                    type: string
                  self:
                    type: string
              self:
                type: string
              type:
                type: string

        404: 
          description: Not Found Device
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string

        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string

    post:
      description: Create an externalId for a managedObject
      summary: Create an externalId for a managedObject
      tags:
        - Identity
      consumes:
        - application/json 
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            type: object
            properties:
              type:
                type: string
              externalId:
                type: string     
        - name: deviceId
          in: path
          required: true
          type: string
          description: unique device ID
      responses:
        201:
          description: Success
          schema:
            type: object
            properties:
              externalId:
                type: string
              managedObject:
                type: object
                properties:
                  id:
                    type: string
                  self:
                    type: string
              self:
                type: string
              type:
                type: string

        default:
          description: Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string

  /identity/externalIds/{externalIdType}/{externalId}:
    get:
      description: Get ManagedObject for a specific externalId
      summary: Get ManagedObject for a specific externalId
      tags:
        - Identity
      produces:
        - application/json
      parameters:
        - name: externalIdType
          in: path
          required: true
          type: string
          description: ''
        - name: externalId
          in: path
          required: true
          type: string
          description: ''
      responses:
        200:
          description: Found Device
          schema:
            type: object
            properties:
              externalId:
                type: string
              managedObject:
                type: object
                properties:
                  id:
                    type: string
                  self:
                    type: string
              self:
                type: string
              type:
                type: string

        404: 
          description: Not Found Device
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string

        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string
          

  /identity/externalIds/{type}/{externalId}:
    delete:
      description: Remove externalId from a managed object
      summary: Remove externalId from a managed object
      tags:
        - Identity
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          required: true
          type: string
          description: ''
        - name: externalId
          in: path
          required: true
          type: string
          description: ''
      responses:
        204:
          description: success

        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string

  /inventory/managedObjects:
    get:
      description: Get Inventory Items
      summary: Get Inventory Items
      tags:
        - Inventory
      produces:
        - application/json
      parameters:
        - in: query
          name: pageSize
          type: integer
        - in: query
          name: query
          type: string

      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              next: 
                type: string
              self:
                type: integer
              statistics:
                type: object
                properties:
                  totalPages:
                    type: integer
                  currentPage:
                    type: integer
                  pageSize:
                    type: integer
              managedObjects:
                type: array
                items:
                  type: object
                  properties:
                    owner: 
                      type: string
                    creationTime: 
                      type: string
                    lastUpdated: 
                      type: string
                    type: 
                      type: string
                    name: 
                      type: string
                    id: 
                      type: string
                    c8y_Position: 
                      type: object
                      properties:
                        lng:
                          type: string
                        lat:
                          type: string
                        alt:
                          type: string
                    c8y_Hardware: 
                      type: object
                      properties:
                        serialNumber:
                          type: string
                        model:
                          type: string

        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string
  
    post:
      description: Add Inventory Item
      summary: Add Device to Inventory
      tags:
        - Inventory
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            type: object
            properties:
              name:
                type: string
              type: 
                type: string
              c8y_IsDevice:
                type: object
              com_cumulocity_model_Agent:
                type: object
              c8y_SupportedMeasurements:
                type: array
              c8y_Hardware:
                type: object
                properties:
                  model:
                    type: string
                  serialNumber:
                    type: string 
              c8y_Mobile:
                type: object
                properties:
                  imei:
                    type: string
                  cellId:
                    type: string 
                  iccid:
                    type: string 
              c8y_Firmware:
                type: object
                properties:
                  version:
                    type: string
              c8y_Position:
                type: object
                properties:
                  alt:
                    type: string
                  lng:
                    type: string 
                  lat:
                    type: string
            
      responses:
        '201':
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              lastUpdated:
                type: string
              name:
                type: string
              owner:
                type: string
              type: 
                type: string
              c8y_Hardware:
                type: object
                properties:
                  model:
                    type: string
                  serialNumber:
                    type: string 
              c8y_Mobile:
                type: object
                properties:
                  imei:
                    type: string
                  cellId:
                    type: string 
                  iccid:
                    type: string 
              c8y_Position:
                type: object
                properties:
                  alt:
                    type: string
                  lng:
                    type: string 
                  lat:
                    type: string
              

        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string


  /tenant/loginOptions:
    get:
      description: Get Tenant Login details
      summary: Get Tenant Login details
      tags:
        - Inventory
      produces:
        - application/json
      parameters:
        - in: header
          name: Host
          type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              loginOptions:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: string
                    visibleOnLoginPage:
                      type: integer
                    buttonName:
                      type: string
                    initRequest:
                      type: string

        default:
          description: server error

  
          
  
  /user/currentUser:
    get:
      description: Get Current user details
      summary: Get current user information
      tags:
        - User
      produces:
        - application/json
      parameters:
        - in: query
          name: dummy
          type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lastName:
                type: string
              userName:
                type: string
              firstName:
                type: string
        401:
          description: Unauthorised
        
        default:
          description: server error
  
  