swagger: "2.0"
info:
  description: Cumulocity REST API for FloPro Integration. This API has been converted from the official Cumulocity Postman Collection.
    https://cumulocity.com/guides/reference/rest-implementation/
  version: "0.1"
  title: Cumulocity REST API

host: cotham.eu-latest.cumulocity.com

schemes:
- https

securityDefinitions:
  auth:
    type: basic

security:
- auth: []

x-ct-server:
  url: '{scheme}://{tenant}.{server}'
  variables:
    - name: scheme
      description: scheme eg https
      type: string
    - name: tenant
      description: tenant name eg cotham
      type: string
    - name: server
      description: server name eg cumulocity.com
      type: string

paths:
 
  /event/events:
    get:
      tags:
      - Events
      summary: Get an event collection
      description: Get an event collection
      produces:
      - application/json
      parameters:
        - in: query
          name: pageSize
          description: Default 5, Max 2000
          type: integer
        - in: query
          name: currentPage
          type: integer
        - in: query
          name: withTotalPages
          type: boolean
        - in: query
          name: dateFrom
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: dateTo
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: fragmentType
          description: fragmentType={fragmentType}
          type: string
        - in: query
          name: type
          description: type={type}
          type: string
        - in: query
          name: source
          description: source={source}
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              self:
                type: string
              events:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    self:
                      type: string
                    creationTime:
                      type: string
                    type:
                      type: string
                    time:
                      type: string
                    text:
                      type: string
                    source:
                      type: object
                      properties:
                        self:
                          type: string
                        id:
                          type: string
                        name:
                          type: string
                        type:
                          type: string
                    statistics:
                      type: object
                      properties:
                        totalPages:
                          type: integer
                        currentPage:
                          type: integer
                        pageSize:
                          type: integer
              prev:
                type: string
              next:
                type: string
        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string
    
  
  /user/currentUser:
    get:
      description: Get the current user
      summary: Get the current user
      tags:
        - Users
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
              self:
                type: string
              userName:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              phone:
                type: string
              email:
                type: string
              enabled:
                type: boolean
        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string
  
  /alarm/alarms/{alarmId}:
    put:
      tags:
      - Alarms
      summary: Update an Alarm
      description: Update an Alarm - Only text, status, severity and custom properties can be modified. Non-modifiable fields will be ignored when provided in request.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: alarmId
        description: Alarm id.
        required: true
        type: string
      - in: body
        name: Alarm
        description: The alarm properties to update
        required: true
        schema:
          type: object
          properties:
            text:
              type: string
            status:
              type: string
            severity:
              type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              self:
                type: integer
              id:
                type: string
              time:
                type: string
              type:
                type: string
              creationTime:
                type: integer
              text:
                type: string
              status:
                type: string
              severity:
                type: string
              count:
                type: integer
              firstOccurrenceTime:
                type: string
              source:
                type: object
                properties:
                  self:
                    type: string
                  id:
                    type: string
                  name:
                    type: string
                  type:
                    type: string
        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string
  
  /alarm/alarms:
    put:
      tags:
      - Alarms
      summary: Bulk update of alarm collection
      description: Bulk update of alarm collection. The PUT method allows for updating alarms collections. Currently only the status of alarms can be changed.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: status
        description: Comma separated alarm statuses, for example ACTIVE,CLEARED.
        type: string
      - in: query
        name: source
        description: Source device id.
        type: string
      - in: query
        name: resolved
        description: When set to true only resolved alarms will be updated (the one with status CLEARED), false means alarms with status ACTIVE or ACKNOWLEDGED.
        type: boolean
      - in: query
        name: severity
        description: Alarm severity, for example MINOR.
        type: string
      - in: query
        name: dateFrom
        description: Start date or date and time of alarm occurrence. Example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
        type: string
      - in: query
        name: dateTo
        description: End date or date and time of alarm occurrence. Example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
        type: string
      - in: body
        name: Status
        description: The status to update
        required: true
        schema:
          type: object
          properties:
            status:
              type: string
      responses:
        200:
          description: Updated
        202:
          description: Process continuing in background
        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string
    
    get:
      tags:
      - Alarms
      summary: Get an alarm collection
      description: Get an alarm collection
      produces:
      - application/json
      parameters:
        - in: query
          name: pageSize
          description: Default 5, Max 2000
          type: integer
        - in: query
          name: currentPage
          type: integer
        - in: query
          name: withTotalPages
          type: boolean
        - in: query
          name: dateFrom
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: dateTo
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: status
          description: status={status}
          type: string
        - in: query
          name: resolved
          description: resolved={resolved}
          type: string
        - in: query
          name: severity
          description: severity={severity}
          type: string
        - in: query
          name: source
          description: source={source}
          type: string
        - in: query
          name: withAssets
          description: withAssets={withAssets}
          type: string
        - in: query
          name: withDevices
          description: withDevices={withDevices}
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              next:
                type: string
              prev:
                type: string
              self:
                type: integer
              statistics:
                type: object
                properties:
                  totalPages:
                    type: integer
                  currentPage:
                    type: integer
                  pageSize:
                    type: integer
              alarms:
                type: array
                items:
                  type: object
                  properties:
                    self:
                      type: integer
                    id:
                      type: string
                    time:
                      type: string
                    type:
                      type: string
                    creationTime:
                      type: integer
                    text:
                      type: string
                    status:
                      type: string
                    severity:
                      type: string
                    count:
                      type: integer
                    firstOccurrenceTime:
                      type: string
                    source:
                      type: object
                      properties:
                        self:
                          type: string
                        id:
                          type: string
                        name:
                          type: string
                        type:
                          type: string
        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string
