swagger: '2.0'
info:
  version: '0.1'
  title: Cumulocity REST API
  description: Cumulocity REST API

host: cotham.eu-latest.cumulocity.com
basePath: 

schemes:
  - https

securityDefinitions:
  auth:
    type: basic
security:
  - auth: []

paths:
  
  /inventory/managedObjects/{deviceId}/childDevices:
    get:
      description: Get Child Inventory Items
      summary: Get Child Inventory Items
      tags:
        - Inventory
      produces:
        - application/json
      parameters:
        - name: deviceId
          in: path
          required: true
          type: string
          description: device ID of parent
        - in: query
          name: pageSize
          description: Default 5, Max 2000
          type: integer
        - in: query
          name: currentPage
          type: integer
        - in: query
          name: withTotalPages
          type: boolean
        - in: query
          name: dateFrom
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: dateTo
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: query
          description: 'query language eg only query to database: …?query=name eq ‘M01’
                        keyword $filter=: …?query=$filter=name eq ‘M01’
                        keyword $orderby=: …?query=$orderby=id asc
                        keywords $filter= and $orderby=: …?query=$filter=name eq ‘M01’ $orderby=id'
          type: string
        - in: query
          name: fragmentType
          description: fragmentType={fragmentType}
          type: string
        - in: query
          name: type
          description: type={type}
          type: string
        - in: query
          name: ids
          description: ids={ids}
          type: string

      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              next: 
                type: string
              self:
                type: integer
              statistics:
                type: object
                properties:
                  totalPages:
                    type: integer
                  currentPage:
                    type: integer
                  pageSize:
                    type: integer
              managedObjects:
                type: array
                items:
                  type: object
                  properties:
                    owner: 
                      type: string
                    creationTime: 
                      type: string
                    lastUpdated: 
                      type: string
                    type: 
                      type: string
                    name: 
                      type: string
                    id: 
                      type: string
                    c8y_Hardware:
                      type: object
                      properties:
                        model:
                          type: string
                        serialNumber:
                          type: string 
                    c8y_Mobile:
                      type: object
                      properties:
                        imei:
                          type: string
                        cellId:
                          type: string 
                        iccid:
                          type: string 
                    c8y_Firmware:
                      type: object
                      properties:
                        version:
                          type: string
                    c8y_Position:
                      type: object
                      properties:
                        alt:
                          type: string
                        lng:
                          type: string 
                        lat:
                          type: string

        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string

  /inventory/managedObjects:
    get:
      description: Get Inventory Items
      summary: Get Inventory Items
      tags:
        - Inventory
      produces:
        - application/json
      parameters:
        - in: query
          name: pageSize
          description: Default 5, Max 2000
          type: integer
        - in: query
          name: currentPage
          type: integer
        - in: query
          name: withTotalPages
          type: boolean
        - in: query
          name: dateFrom
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: dateTo
          description: example formats 2019-04-20 or 2019-04-20T08:30:00.000Z
          type: string
        - in: query
          name: query
          description: 'query language eg only query to database: …?query=name eq ‘M01’
                        keyword $filter=: …?query=$filter=name eq ‘M01’
                        keyword $orderby=: …?query=$orderby=id asc
                        keywords $filter= and $orderby=: …?query=$filter=name eq ‘M01’ $orderby=id'
          type: string
        - in: query
          name: fragmentType
          description: fragmentType={fragmentType}
          type: string
        - in: query
          name: type
          description: type={type}
          type: string
        - in: query
          name: ids
          description: ids={ids}
          type: string

      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              next: 
                type: string
              self:
                type: integer
              statistics:
                type: object
                properties:
                  totalPages:
                    type: integer
                  currentPage:
                    type: integer
                  pageSize:
                    type: integer
              managedObjects:
                type: array
                items:
                  type: object
                  properties:
					childAssets:
						type: object
						properties:
							references:
								type: array
								items:
									type: object
									properties:
										managedObject:
											type: object
											properties:
												name: 
				                                   type: string
				                                id: 
				                                   type: string			
                    owner: 
                      type: string
                    creationTime: 
                      type: string
                    lastUpdated: 
                      type: string
                    type: 
                      type: string
                    name: 
                      type: string
                    id: 
                      type: string
                    c8y_Hardware:
                      type: object
                      properties:
                        model:
                          type: string
                        serialNumber:
                          type: string 
                    c8y_Mobile:
                      type: object
                      properties:
                        imei:
                          type: string
                        cellId:
                          type: string 
                        iccid:
                          type: string 
                    c8y_Firmware:
                      type: object
                      properties:
                        version:
                          type: string
                    c8y_Position:
                      type: object
                      properties:
                        alt:
                          type: string
                        lng:
                          type: string 
                        lat:
                          type: string

        default:
          description: Other Error
          schema:
            type: object
            properties:
              error:
                type: string
              info:
                type: string
              message:
                type: string
  
    