swagger: '2.0'
info:
  version: "1.0"
  title: 'Air Table Visitor Management'
  description: 'Air Table Visitor Management Demo App'

host: api.airtable.com
basePath: /v0

schemes:
  - https

paths:

  /{baseid}/Visitors/{id}:
    get:
      summary: Get Single Visit Record
      description: Get Single Visit Record
      tags:
        - Visits
      produces:
        - application/json
      parameters:
        - in: path
          name: baseid
          description: baseId
          type: string
          required: true
        - in: path
          name: id
          description: Id
          type: string
          required: true
        - in: header
          name: Authorization
          description: bearer token
          type: string

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id: 
                type: string
              fields: 
                type: object
                properties: 
                  Visiting: 
                    type: array
                    items: 
                      type: string
                  Last Name: 
                    type: string
                  Company: 
                    type: string
                  First Name: 
                    type: string
                  Reason for visit: 
                    type: string
                  Full Name: 
                    type: string
                  Date/Time of Visit: 
                    type: string
              createdTime: 
                type: string
        
        default:
          description: error

    put:
      summary: PUT - Update Visit Record
      description: PUT - Update Visit Record
      tags:
        - Visits
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: baseid
          description: baseId
          type: string
          required: true
        - in: path
          name: id
          description: Id
          type: string
          required: true
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - name: body
          in: body
          required: true
          description: ""
          schema:
            type: object
            properties:
              records: 
                type: array
                items: 
                  type: object
                  properties: 
                    id: 
                      type: string
                    fields: 
                      type: object
                      properties: 
                        Visiting: 
                          type: array
                          items: 
                            type: string
                        Company: 
                          type: string
                        Reason for visit: 
                          type: string
                        First Name: 
                          type: string
                        Last Name: 
                          type: string

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              records: 
                type: array
                items: 
                  type: object
                  properties: 
                    id: 
                      type: string
                    fields: 
                      type: object
                      properties: 
                        Visiting: 
                          type: array
                          items: 
                            type: string
                        Last Name: 
                          type: string
                        Company: 
                          type: string
                        First Name: 
                          type: string
                        Reason for visit: 
                          type: string
                        Full Name: 
                          type: string
                        Date/Time of Visit: 
                          type: string
                    createdTime: 
                      type: string

        
        default:
          description: error

    patch:
      summary: PATCH - Update Visit Record
      description: PATCH - Update Visit Record
      tags:
        - Visits
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: baseid
          description: baseId
          type: string
          required: true
        - in: path
          name: id
          description: Id
          type: string
          required: true
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - name: body
          in: body
          required: true
          description: ""
          schema:
            type: object
            properties:
              records: 
                type: array
                items: 
                  type: object
                  properties: 
                    id: 
                      type: string
                    fields: 
                      type: object
                      properties: 
                        Visiting: 
                          type: array
                          items: 
                            type: string
                        Company: 
                          type: string
                        Reason for visit: 
                          type: string
                        First Name: 
                          type: string
                        Last Name: 
                          type: string

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              records: 
                type: array
                items: 
                  type: object
                  properties: 
                    id: 
                      type: string
                    fields: 
                      type: object
                      properties: 
                        Visiting: 
                          type: array
                          items: 
                            type: string
                        Last Name: 
                          type: string
                        Company: 
                          type: string
                        First Name: 
                          type: string
                        Reason for visit: 
                          type: string
                        Full Name: 
                          type: string
                        Date/Time of Visit: 
                          type: string
                    createdTime: 
                      type: string

        default:
          description: error

    delete:
      summary: Delete Visit Record
      description: Delete Visit Record
      tags:
        - Visits
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: baseid
          description: baseId
          type: string
          required: true
        - in: path
          name: id
          description: Id
          type: string
          required: true
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: formData
          name: records[]
          type: string
          description: id of record for deletion
          required: true
        
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              records: 
                type: array
                items: 
                  type: object
                  properties: 
                    id: 
                      type: string
                    deleted: 
                      type: boolean

        default:
          description: error

  /{baseid}/Visitors:
    post:
      summary: Create Visit Record
      description: Create Visit Record
      tags:
        - Visits
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          name: baseid
          description: baseId
          type: string
          required: true
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - name: body
          in: body
          required: true
          description: ""
          schema:
            type: object
            properties:
              records: 
                type: array
                items: 
                  type: object
                  properties: 
                    fields: 
                      type: object
                      properties: 
                        Visiting: 
                          type: array
                          items: 
                            type: string
                        Company: 
                          type: string
                        Reason for visit: 
                          type: string
                        First Name: 
                          type: string
                        Last Name: 
                          type: string

      responses:
        201:
          description: OK
          schema:
            type: object
            properties:
              records: 
                type: array
                items: 
                  type: object
                  properties: 
                    id: 
                      type: string
                    fields: 
                      type: object
                      properties: 
                        Visiting: 
                          type: array
                          items: 
                            type: string
                        Last Name: 
                          type: string
                        Company: 
                          type: string
                        First Name: 
                          type: string
                        Reason for visit: 
                          type: string
                        Full Name: 
                          type: string
                        Date/Time of Visit: 
                          type: string
                    createdTime: 
                      type: string
        default:
          description: error

    get:
      summary: List Visit Records
      description: List Visit Records
      tags:
        - Visits
      produces:
        - application/json
      parameters:
        - in: path
          name: baseid
          description: baseId
          type: string
          required: true
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: query
          name: filterByFormula
          type: string
          description: filter by formula
          required: false
        - in: query
          name: sort
          type: string
          description: sort by field
          required: false
        - in: query
          name: view
          type: string
          description: select a view
          required: false
        - in: query
          name: fields
          type: string
          description: select fields
          required: false
        - in: query
          name: maxRecords
          type: string
          description: select fields
          required: false
      

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              records: 
                type: array
                items: 
                  type: object
                  properties: 
                    id: 
                      type: string
                    fields: 
                      type: object
                      properties: 
                        Visiting: 
                          type: array
                          items: 
                            type: string
                        Last Name: 
                          type: string
                        Company: 
                          type: string
                        First Name: 
                          type: string
                        Reason for visit: 
                          type: string
                        Full Name: 
                          type: string
                        Date/Time of Visit: 
                          type: string
                    createdTime: 
                      type: string
              offset: 
                type: string
        default:
          description: error
          

  