swagger: '2.0'
info:
  version: "1.0"
  title: 'TPOM App'
  description: 'TPOM App'

host: api.airtable.com
basePath: /v0

schemes:
  - https

paths:
  
  /{baseid}/Days:
    get:
      summary: List Days
      description: List Days
      produces:
        - application/json
      parameters:
        - in: path
          name: baseid
          description: baseId
          type: string
          required: true
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: query
          name: filterByFormula
          type: string
          description: filter by formula
          required: false
        - in: query
          name: sort
          type: string
          description: sort by field
          required: false
        - in: query
          name: view
          type: string
          description: select a view
          required: false
        - in: query
          name: fields
          type: string
          description: select fields
          required: false
        - in: query
          name: maxRecords
          type: string
          description: select fields
          required: false
      

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              records: 
                type: array
                items: 
                  type: object
                  properties: 
                    id: 
                      type: string
                    fields: 
                      type: object
                      properties: 
                        ImageURL1: 
                          type: string
                        ImageURL2: 
                          type: string
                        Practical Description: 
                          type: string
                        audioURL1: 
                          type: string
                        audioURL2: 
                          type: string
                        Name: 
                          type: string
                        Description: 
                          type: string
                        Audio1Name:
                          type: string
                        Audio2Name:
                          type: string
                        audio1Time:
                          type: string
                        audio2Time:
                          type: string
                        Sort:
                          type: string
                        additionalInfoURL:
                          type: string
                        additionalInfoType:
                          type: string
                    createdTime: 
                      type: string
              offset: 
                type: string
        default:
          description: error
          

  