swagger: '2.0'
info:
  version: "1.0"
  title: 'WB18 Festival'
  description: 'WB18 Festival Airtable Demo'

host: api.airtable.com
basePath: /v0/appMRqzoh8hP79b1B

schemes:
  - https


paths:

  /Diary:
    get:
      summary: list Diary
      description: list Diary
      tags:
        - WB18
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: query
          name: filterByFormula
          type: string
          description: filter by formula
          required: false
        - in: query
          name: sort
          type: string
          description: sort by field
          required: false
        - in: query
          name: view
          type: string
          description: select a view
          required: false
      

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              records:
                type: array
                items:
                  type: object 
                  properties:
                    id:
                      type: string
                    fields:
                      type: object
                      properties:
                        Name:
                          type: string
                        Date:
                          type: string
                        Image:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                              url:
                                type: string
                              filename:
                                type: string
                              size:
                                type: string  
                              type:
                                type: string
                              thumbnails:
                                type: object
                                properties:
                                  small:
                                    type: object 
                                    properties:
                                      url:
                                        type: string
                                      width:
                                        type: string
                                      height:
                                        type: string
                                  large:
                                    type: object 
                                    properties:
                                      url:
                                        type: string
                                      width:
                                        type: string
                                      height:
                                        type: string
                                  full:
                                    type: object 
                                    properties:
                                      url:
                                        type: string
                                      width:
                                        type: string
                                      height:
                                        type: string



                    createdTime:
                      type: string


  /Events:
    get:
      summary: list Events
      description: list Events
      tags:
        - WB18
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: query
          name: filterByFormula
          type: string
          description: filter by formula
          required: false
        - in: query
          name: sort
          type: string
          description: sort by field
          required: false
        - in: query
          name: view
          type: string
          description: select a view
          required: false
      

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              records:
                type: array
                items:
                  type: object 
                  properties:
                    id:
                      type: string
                    fields:
                      type: object
                      properties:
                        eventCode:
                          type: string
                        eventStart:
                          type: string
                        eventEnd:
                          type: string
                        eventName:
                          type: string
                        artistCode:
                          type: string
                        venueCode:
                          type: string
                        eventDescription:
                          type: string
                        eventImage:
                          type: string

                    createdTime:
                      type: string

  /Venues:
    get:
      summary: list venues
      description: list venues
      tags:
        - WB18
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: query
          name: filterByFormula
          type: string
          description: filter by formula
          required: false
        - in: query
          name: sort
          type: string
          description: sort by field
          required: false
        - in: query
          name: view
          type: string
          description: select a view
          required: false
      

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              records:
                type: array
                items:
                  type: object 
                  properties:
                    id:
                      type: string
                    fields:
                      type: object
                      properties:
                        venueCode:
                          type: string
                        venueName:
                          type: string
                        venueAddress:
                          type: string
                        venuePostcode:
                          type: string
                        venuePhone:
                          type: string
                        venueTimes:
                          type: string
                        venueUrl:
                          type: string
                        venueLat:
                          type: string
                        venueLong:
                          type: string
                        venueImage:
                          type: string
                    createdTime:
                      type: string

  /Artists:
    get:
      summary: list artists
      description: list artists
      tags:
        - WB18
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: query
          name: filterByFormula
          type: string
          description: filter by formula
          required: false
        - in: query
          name: sort
          type: string
          description: sort by field
          required: false
        - in: query
          name: view
          type: string
          description: select a view
          required: false
      

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              records:
                type: array
                items:
                  type: object 
                  properties:
                    id:
                      type: string
                    fields:
                      type: object
                      properties:
                        artistCode:
                          type: string
                        artistName:
                          type: string
                        artistBiog:
                          type: string
                        artistUrl:
                          type: string
                        artistimageLg:
                          type: string
                    createdTime:
                      type: string

    post:
      summary: create artists
      description: create artists
      tags:
        - WB18
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: body
          name: body
          schema:
            type: object
            properties:
              records:
                type: array
                items:
                  type: object 
                  properties:
                    fields:
                      type: object
                      properties:
                        artistCode:
                          type: string
                        artistName:
                          type: string
                        artistBiog:
                          type: string
                        artistUrl:
                          type: string
                        artistimageLg:
                          type: string   
  
      responses:
        200:
          description: Saved
          schema:
            type: object
            properties:
              records:
                type: array
                items:
                  type: object 
                  properties:
                    id:
                      type: string
                    fields:
                      type: object
                      properties:
                        artistCode:
                          type: string
                        artistName:
                          type: string
                        artistBiog:
                          type: string
                        artistUrl:
                          type: string
                        artistimageLg:
                          type: string
                    createdTime:
                      type: string       