produces:
    - text/plain
    - application/json
    - text/json
schemes:
    - https
swagger: "2.0"
info:
    description: Cotham-AgileBase Timesheets service
    title: Cotham-AgileBase Timesheets service
    version: v1.0
host: https://cloud.agilebase.co.uk/agileBase
paths:

  /Public.ab/:
    post:
      summary: Timesheets service
      description: Timesheets service
      tags:
        - 1. Driver App
      consumes:
        - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          description: token
          required: true
          
        - in: body
          name: t
          type: string
          description: Table ID
          required: true
          
        - in: body
          name: c
          type: string
          description: Company ID
          required: true
        
        - in: body
          name: update_record
          type: string
          description: Company ID
          default: true
          required: true
        
        - in: body
          name: row_id
          type: string
          description: Row ID
          required: true
        
        - in: body
          name: includeslunch_sionsfhtd0
          type: string
          description: Includes Lunch
          required: true
        
        - in: body
          name: attendance_onsfht
          type: string
          description: Went Ahead
          required: true
        
        - in: body
          name: location_nsfh
          type: string
          description: Location
          required: true
        
        - in: body
          name: reason_sf
          type: string
          description: Reason
          required: true

        - in: body
          name: hoursworked_ionsfhtd
          type: string
          description: Hours worked with client
          required: true

        - in: body
          name: mileage_nsfh
          type: string
          description: Mileage
          required: true

        - in: body
          name: notesaboutmilea_ssionsfhtd0q
          type: string
          description: Notes (about mileage/expenses only)
          required: true

        
        
      responses:
        200:
          description: Return a standard response format for JSONRPC - if responseCode in this response is a success (1). Any other response code is an error.
          schema:
            type: object
            properties:
              responseCode:
                type: integer
              responseMessage:
                type: string
              payload:
                type: array
                items:
                  type: object
                  properties: 
                    User_Name: 
                      type: string
                    Company_Name: 
                      type: string
                    Waste_Employee_No: 
                      type: string
                    Name: 
                      type: string
                    Address: 
                      type: string
                    Address_2: 
                      type: string
                    County: 
                      type: string
                    City: 
                      type: string
                    Post_Code: 
                      type: string
                    Country_Region_Code:
                      type: string
                    Phone_No: 
                      type: string
                    E_Mail: 
                      type: string
                    E_Mail_2: 
                      type: string
                    Home_Page: 
                      type: string
                    AuxiliaryIndex1: 
                      type: string
                    AuxiliaryIndex2: 
                      type: string
                    AuxiliaryIndex3: 
                      type: string
                    AuxiliaryIndex4: 
                      type: string
                    AuxiliaryIndex5: 
                      type: string
                    User_Security_ID_FilterOnly: 
                      type: string
              sessionToken:
                type: string
              requestedMethod:
                type: string
              requestedFormat:
                type: string
              timestamp:
                type: string
                format: time
              requestReceivedTime:
                type: string
                format: time
              maxAllowedRequestTime:
                type: integer 
              requestProcessingTime:
                type: string
                format: double
                
        default:
          description: Failed Server Response
