swagger: '2.0'
info:
  version: '2.0'
  title: 'Google Firestore Def for Demo Books App'
  description: ''
host: firestore.googleapis.com
basePath: /v1/projects
schemes: 
  - https


paths:

  /{projectID}/databases/(default)/documents/{collectionId}/{userId}/{subcollectionId}:
    get:
      summary: list users books
      description: list users books
      tags: 
        - documents
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: path
          name: projectID
          description: firebase app project projectID
          type: string
          required: true
        - in: path
          name: collectionId
          type: string
          required: true
        - in: path
          name: userId
          type: string
          required: true
        - in: path
          name: subcollectionId
          type: string
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              documents: 
                type: array
                items: 
                  type: object
                  properties: 
                    name: 
                      type: string
                    fields: 
                      type: object
                      properties: 
                        status: 
                          type: object
                          properties: 
                            stringValue: 
                              type: string
                        title: 
                          type: object
                          properties: 
                            stringValue: 
                              type: string
                    createTime: 
                      type: string
                    updateTime: 
                      type: string
        default:
          description: unexpected response  

    post:
      summary: add book entry
      description: add book entry
      tags: 
        - documents
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: bearer token
          type: string
        - in: path
          name: projectID
          description: firebase app project projectID
          type: string
          required: true
        - in: path
          name: collectionId
          type: string
          required: true
        - in: path
          name: userId
          type: string
          required: true
        - in: path
          name: subcollectionId
          type: string
          required: true
        - in: body
          name: body
          schema:
            type: object
            properties:
              fields:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      stringValue:
                        type: string
                  title:
                    type: object
                    properties:
                      stringValue:
                        type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              name: 
                type: string
              fields: 
                type: object
                properties: 
                  status: 
                    type: object
                    properties: 
                      stringValue: 
                        type: string
                  title: 
                    type: object
                    properties: 
                      stringValue: 
                        type: string
              createTime: 
                type: string
              updateTime: 
                type: string

        default:
          description: unexpected response  
    