swagger: '2.0'
info:
  title: FloDB Table myorders6
  version: '1.0'
host: e4ne3a7yg6.execute-api.eu-west-2.amazonaws.com
basePath: /dev
schemes:
  - https
paths:
  /flodb/59e8d1c0-16ad-404b-9a65-12ae78b101e0/myorders6-f0a53f19-895a-4920-8d38-62b2be478399/deleteall:
    post:
      summary: Delete All Records
      description: Delete All Records from myorders6 Table
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          name: x-api-key
          type: string
      responses:
        '204':
          description: Success
          schema:
            type: object
            properties:
              result:
                type: string
              resultMessage:
                type: string
        default:
          description: Error
          schema:
            type: object
            properties:
              result:
                type: string
              resultMessage:
                type: string
  /flodb/59e8d1c0-16ad-404b-9a65-12ae78b101e0/myorders6-f0a53f19-895a-4920-8d38-62b2be478399/{recordId}/read:
    post:
      summary: Get Record
      description: Get Single Record from myorders6
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          name: x-api-key
          type: string
        - in: path
          name: recordId
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              payload:
                type: object
                properties:
                  Item:
                    type: object
                    properties:
                      recordId:
                        type: string
                      isoDateTimeUpdatedAt:
                        type: string
                      isoDateTimeCreatedAt:
                        type: string
                      itemData:
                        type: object
                        properties:
                          orderNumber:
                            type: string
                          customerNumber:
                            type: string
                          customerName:
                            type: string
              result:
                type: string
              resultMessage:
                type: string
        default:
          description: Error
          schema:
            type: object
            properties:
              result:
                type: string
              resultMessage:
                type: string
  /flodb/59e8d1c0-16ad-404b-9a65-12ae78b101e0/myorders6-f0a53f19-895a-4920-8d38-62b2be478399/{recordId}/update:
    post:
      summary: Update Record
      description: Update myorders6 Record
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          name: x-api-key
          type: string
        - in: path
          name: recordId
          type: string
          required: true
        - name: request
          in: body
          required: true
          schema:
            type: object
            properties:
              orderNumber:
                type: string
              customerNumber:
                type: string
              customerName:
                type: string
      responses:
        '201':
          description: Success
          schema:
            type: object
            properties:
              payload:
                type: object
              result:
                type: string
              resultMessage:
                type: string
        default:
          description: Error
          schema:
            type: object
            properties:
              result:
                type: string
              resultMessage:
                type: string
  /flodb/59e8d1c0-16ad-404b-9a65-12ae78b101e0/myorders6-f0a53f19-895a-4920-8d38-62b2be478399/{recordId}/delete:
    post:
      summary: Delete Record
      description: Delete myorders6 Record
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          name: x-api-key
          type: string
        - in: path
          name: recordId
          type: string
          required: true
      responses:
        '204':
          description: Success
          schema:
            type: object
            properties:
              result:
                type: string
              resultMessage:
                type: string
        default:
          description: Error
          schema:
            type: object
            properties:
              result:
                type: string
              resultMessage:
                type: string
  /flodb/59e8d1c0-16ad-404b-9a65-12ae78b101e0/myorders6-f0a53f19-895a-4920-8d38-62b2be478399/create:
    post:
      summary: Create Record
      description: Create myorders6 Record
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          name: x-api-key
          type: string
        - name: request
          in: body
          required: true
          schema:
            type: object
            properties:
              orderNumber:
                type: string
              customerNumber:
                type: string
              customerName:
                type: string
      responses:
        '201':
          description: Success
          schema:
            type: object
            properties:
              result:
                type: string
              resultMessage:
                type: string
        default:
          description: Error
          schema:
            type: object
            properties:
              result:
                type: string
              resultMessage:
                type: string
  /flodb/59e8d1c0-16ad-404b-9a65-12ae78b101e0/myorders6-f0a53f19-895a-4920-8d38-62b2be478399/query:
    post:
      summary: Query Records
      description: Query myorders6 Records
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: header
          name: x-api-key
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              payload:
                type: object
                properties:
                  Items:
                    type: array
                    items:
                      type: object
                      properties:
                        recordId:
                          type: string
                        isoDateTimeUpdatedAt:
                          type: string
                        isoDateTimeCreatedAt:
                          type: string
                        itemData:
                          type: object
                          properties:
                            orderNumber:
                              type: string
                            customerNumber:
                              type: string
                            customerName:
                              type: string
                  Count:
                    type: number
                  ScannedCount:
                    type: number
              result:
                type: string
              resultMessage:
                type: string
        default:
          description: Error
          schema:
            type: object
            properties:
              result:
                type: string
              resultMessage:
                type: string