swagger: '2.0'
info:
  title: Hotel
  version: 2.0.0
  description: >
    The Hotel Search REST/JSON API is a hotel search API that enables you to
    find the best hotel offers that match your search from a wide choice of
    providers. 

host: test.api.amadeus.com
basePath: /v2
securityDefinitions: {}
schemes:
  - https

paths:
  /shopping/hotel-offers:
    get:
      
      summary: FIND HOTELS.
      tags:
        - shopping
      description: FIND HOTELS
      consumes:
        - application/vnd.amadeus+json
      produces:
        - application/vnd.amadeus+json
      parameters:
        - name: cityCode
          in: query
          required: false
          type: string
        - name: latitude
          in: query
          required: false
          type: number
          format: double
        - name: longitude
          in: query
          required: false
          type: number
          format: double
        - name: radius
          in: query
          required: false
          type: integer
        - name: radiusUnit
          in: query
          required: false
          type: string
        - name: paymentPolicy
          in: query
          required: false
          type: string
        - name: includeClosed
          in: query
          required: false
          type: boolean
          default: false
        - name: bestRateOnly
          in: query
          required: false
          type: boolean
          default: true
        - name: view
          in: query
          description: view FULL LIGHT or NONE
          required: false
          type: string
        - name: sort
          in: query
          required: false
          type: string
        - name: 'page[limit]'
          in: query
          required: false
          type: integer
        - name: 'page[offset]'
          in: query
          required: false
          type: string
      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    hotel:
                      type: object
                      properties:
                        type:
                          type: string
                        hotelId:
                          type: string
                        chainCode:
                          type: string
                        brandCode:
                          type: string
                        dupeId:
                          type: string
                        name:
                          type: string
                        rating:
                          type: string
                        description:
                          type: object
                          properties:
                            lang:
                              type: string
                            text:
                              type: string                 
                        media:
                          type: array
                          items:
                            type: object
                            properties:
                              uri:
                                type: string
                              category:
                                type: string
                        cityCode:
                          type: string
                        latitude:
                          type: number
                        longitude:
                          type: number
                        hotelDistance:
                          type: object
                          properties:
                            distance:
                              type: number
                            distanceUnit:
                              type: string
                        address:
                          properties:
                          postalCode:
                            type: string
                          cityName:
                            type: string
                          countryCode:
                            type: string
                          stateCode:
                            type: string
                        contact:
                          properties:
                            phone:
                              type: string
                            fax:
                              type: string
                            email:
                              type: string
                    available:
                      type: boolean
                    offers:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          id:
                            type: string
                          checkInDate:
                            type: string
                          checkOutDate:
                            type: string
                          roomQuantity:
                            type: integer
                          rateCode:
                            type: string
                          rateFamilyEstimated:
                            type: object
                            properties:
                              code:
                                type: string
                              type:
                                type: string
                    self:
                      type: string

              meta:
                type: object
                properties:
                  links:
                    type: object
                    properties:
                      next:
                        type: string
                  lang:
                    type: string

        default:
          description: other fail