swagger: '2.0'
info:
  title: Power Platform CDS Demo 
  description: Power Platform CDS Demo 
  version: '1.0.0'
host: orgf3cfd067.crm11.dynamics.com
basePath: /api/data/v9.1
schemes:
  - https

paths:
  /accounts:
    get:
      summary: list accounts
      description: list accounts
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Bearer Token
          required: false
        
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              value: 
                type: array
                items: 
                  type: object
                  properties: 
                    address2_addresstypecode: 
                      type: number
                    merged: 
                      type: boolean
                    accountnumber: 
                      type: string
                    statecode: 
                      type: number
                    emailaddress1: 
                      type: string
                    exchangerate: 
                      type: number
                    name: 
                      type: string
                    websiteurl: 
                      type: string
                    _owningbusinessunit_value: 
                      type: string
                    _owninguser_value: 
                      type: string
                    _primarycontactid_value: 
                      type: string
                    importsequencenumber: 
                      type: number
                    address1_composite: 
                      type: string
                    donotpostalmail: 
                      type: boolean
                    accountratingcode: 
                      type: number
                    numberofemployees: 
                      type: number
                    marketingonly: 
                      type: boolean
                    revenue_base: 
                      type: number
                    preferredcontactmethodcode: 
                      type: number
                    _ownerid_value: 
                      type: string
                    customersizecode: 
                      type: number
                    businesstypecode: 
                      type: number
                    donotemail: 
                      type: boolean
                    address2_shippingmethodcode: 
                      type: number
                    revenue: 
                      type: number
                    address2_freighttermscode: 
                      type: number
                    statuscode: 
                      type: number
                    createdon: 
                      type: string
                      format: date-time
                    address1_stateorprovince: 
                      type: string
                    donotsendmm: 
                      type: boolean
                    donotfax: 
                      type: boolean
                    donotbulkpostalmail: 
                      type: boolean
                    address1_country: 
                      type: string
                    versionnumber: 
                      type: number
                    address1_line1: 
                      type: string
                    address1_addressid: 
                      type: string
                    modifiedon: 
                      type: string
                      format: date-time
                    creditonhold: 
                      type: boolean
                    telephone1: 
                      type: string
                    donotphone: 
                      type: boolean
                    _transactioncurrencyid_value: 
                      type: string
                    accountid: 
                      type: string
                    donotbulkemail: 
                      type: boolean
                    _modifiedby_value: 
                      type: string
                    followemail: 
                      type: boolean
                    shippingmethodcode: 
                      type: number
                    _createdby_value: 
                      type: string
                    address1_city: 
                      type: string
                    territorycode: 
                      type: number
                    participatesinworkflow: 
                      type: boolean
                    accountclassificationcode: 
                      type: number
                    address2_addressid: 
                      type: string
                    address1_postalcode: 
                      type: string
                    overriddencreatedon: 
                      type: string
                      format: nullable
                    address1_postofficebox: 
                      type: string
                      format: nullable
                    address1_name: 
                      type: string
                      format: nullable
                    address1_telephone3: 
                      type: string
                      format: nullable
                    address2_county: 
                      type: string
                      format: nullable
                    address1_line2: 
                      type: string
                      format: nullable
                    timespentbymeonemailandmeetings: 
                      type: string
                      format: nullable
                    address1_county: 
                      type: string
                      format: nullable
                    address2_longitude: 
                      type: string
                      format: nullable
                    ownershipcode: 
                      type: string
                      format: nullable
                    timezoneruleversionnumber: 
                      type: string
                      format: nullable
                    address1_telephone1: 
                      type: string
                      format: nullable
                    primarysatoriid: 
                      type: string
                      format: nullable
                    _masterid_value: 
                      type: string
                      format: nullable
                    address2_latitude: 
                      type: string
                      format: nullable
                    address2_fax: 
                      type: string
                      format: nullable
                    aging60_base: 
                      type: string
                      format: nullable
                    aging90: 
                      type: string
                      format: nullable
                    accountcategorycode: 
                      type: string
                      format: nullable
                    industrycode: 
                      type: string
                      format: nullable
                    processid: 
                      type: string
                      format: nullable
                    address1_latitude: 
                      type: string
                      format: nullable
                    tickersymbol: 
                      type: string
                      format: nullable
                    address2_name: 
                      type: string
                      format: nullable
                    address1_line3: 
                      type: string
                      format: nullable
                    paymenttermscode: 
                      type: string
                      format: nullable
                    fax: 
                      type: string
                      format: nullable
                    emailaddress3: 
                      type: string
                      format: nullable
                    address2_utcoffset: 
                      type: string
                      format: nullable
                    entityimage: 
                      type: string
                      format: nullable
                    ftpsiteurl: 
                      type: string
                      format: nullable
                    address2_city: 
                      type: string
                      format: nullable
                    _owningteam_value: 
                      type: string
                      format: nullable
                    marketcap: 
                      type: string
                      format: nullable
                    aging30: 
                      type: string
                      format: nullable
                    entityimage_url: 
                      type: string
                      format: nullable
                    sharesoutstanding: 
                      type: string
                      format: nullable
                    aging60: 
                      type: string
                      format: nullable
                    stageid: 
                      type: string
                      format: nullable
                    preferredappointmenttimecode: 
                      type: string
                      format: nullable
                    address2_composite: 
                      type: string
                      format: nullable
                    aging90_base: 
                      type: string
                      format: nullable
                    address1_upszone: 
                      type: string
                      format: nullable
                    description: 
                      type: string
                      format: nullable
                    onholdtime: 
                      type: string
                      format: nullable
                    marketcap_base: 
                      type: string
                      format: nullable
                    address2_stateorprovince: 
                      type: string
                      format: nullable
                    yominame: 
                      type: string
                      format: nullable
                    address2_telephone3: 
                      type: string
                      format: nullable
                    _slainvokedid_value: 
                      type: string
                      format: nullable
                    address1_primarycontactname: 
                      type: string
                      format: nullable
                    _slaid_value: 
                      type: string
                      format: nullable
                    traversedpath: 
                      type: string
                      format: nullable
                    stockexchange: 
                      type: string
                      format: nullable
                    _createdonbehalfby_value: 
                      type: string
                      format: nullable
                    _modifiedbyexternalparty_value: 
                      type: string
                      format: nullable
                    address2_telephone1: 
                      type: string
                      format: nullable
                    address2_line3: 
                      type: string
                      format: nullable
                    address2_postalcode: 
                      type: string
                      format: nullable
                    address1_shippingmethodcode: 
                      type: string
                      format: nullable
                    entityimage_timestamp: 
                      type: string
                      format: nullable
                    address2_primarycontactname: 
                      type: string
                      format: nullable
                    primarytwitterid: 
                      type: string
                      format: nullable
                    customertypecode: 
                      type: string
                      format: nullable
                    address2_line1: 
                      type: string
                      format: nullable
                    address2_postofficebox: 
                      type: string
                      format: nullable
                    address1_freighttermscode: 
                      type: string
                      format: nullable
                    address1_longitude: 
                      type: string
                      format: nullable
                    telephone2: 
                      type: string
                      format: nullable
                    address1_addresstypecode: 
                      type: string
                      format: nullable
                    lastusedincampaign: 
                      type: string
                      format: nullable
                    _preferredsystemuserid_value: 
                      type: string
                      format: nullable
                    creditlimit_base: 
                      type: string
                      format: nullable
                    telephone3: 
                      type: string
                      format: nullable
                    preferredappointmentdaycode: 
                      type: string
                      format: nullable
                    _modifiedonbehalfby_value: 
                      type: string
                      format: nullable
                    utcconversiontimezonecode: 
                      type: string
                      format: nullable
                    _createdbyexternalparty_value: 
                      type: string
                      format: nullable
                    sic: 
                      type: string
                      format: nullable
                    creditlimit: 
                      type: string
                      format: nullable
                    lastonholdtime: 
                      type: string
                      format: nullable
                    address2_line2: 
                      type: string
                      format: nullable
                    address1_telephone2: 
                      type: string
                      format: nullable
                    aging30_base: 
                      type: string
                      format: nullable
                    entityimageid: 
                      type: string
                      format: nullable
                    address1_fax: 
                      type: string
                      format: nullable
                    address2_upszone: 
                      type: string
                      format: nullable
                    address2_country: 
                      type: string
                      format: nullable
                    address1_utcoffset: 
                      type: string
                      format: nullable
                    emailaddress2: 
                      type: string
                      format: nullable
                    _parentaccountid_value: 
                      type: string
                      format: nullable
                    address2_telephone2: 
                      type: string
                      format: nullable
                  