swagger: '2.0'
info:
  description: SR Mock
  version: 1.0.0
  title: SR Mock


# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /CothamTechnologies/SR-Mock/1.0
schemes:
 - https

paths:

  /getReferenceData:
    get:
      summary: SR Get Ref data
      description: SR Get Ref data
      tags:
        - Service Robotics
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              privileges:
                type: array
                items:
                  type: object
                  properties:
                    value:
                      type: string
                    description: 
                      type: string
              hotdrinks:
                type: array
                items:
                  type: object
                  properties:
                    value:
                      type: string
                    description: 
                      type: string
              yesNo:
                  type: array
                  items:
                    type: object
                    properties:
                      value:
                        type: string
                      description: 
                        type: string
              maritalStatus:
                  type: array
                  items:
                    type: object
                    properties:
                      value:
                        type: string
                      description: 
                        type: string
              languages:
                  type: array
                  items:
                    type: object
                    properties:
                      value:
                        type: string
                      description: 
                        type: string
              sports:
                  type: array
                  items:
                    type: object
                    properties:
                      value:
                        type: string
                      description: 
                        type: string
              colours:
                  type: array
                  items:
                    type: object
                    properties:
                      value:
                        type: string
                      description: 
                        type: string
              entertainment:
                  type: array
                  items:
                    type: object
                    properties:
                      value:
                        type: string
                      description: 
                        type: string
              shops:
                  type: array
                  items:
                    type: object
                    properties:
                      value:
                        type: string
                      description: 
                        type: string
              support:
                  type: array
                  items:
                    type: object
                    properties:
                      value:
                        type: string
                      description: 
                        type: string
              
        default:
          description: server error
  
  /login:
    get:
      summary: login
      description: login
      produces:
      - application/json
      parameters:
      - in: query
        name: email
        type: string
        description: email
        required: true
      - in: query
        name: password
        type: string
        description: password
        required: true 
     
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
              expiry:
                type: string
              username:
                type: string
              startingScriptURL:
                type: string

                
        default:
          description: server error
  
  /getleads:
    get:
      summary: SR get leads
      description: SR get leads
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              leads:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      type: string
                    firstName:
                      type: string
                    surname:
                      type: string
                    addressFull:
                      type: string
                    addressLine1:
                      type: string
                    addressLine2:
                      type: string
                    addressCityTown:
                      type: string
                    addressCounty:
                      type: string
                    addressPostcode:
                      type: string
                    addressCountry:
                      type: string
                    telephone:
                      type: string
                    email:
                      type: string
                    introStatus: 
                      type: string
                    introCompletedTime:
                      type: string
                    introCompletedLat:
                      type: string
                    introCompletedLong:
                      type: string
                    suitabilityStatus: 
                      type: string
                    suitabilityCompletedTime:
                      type: string
                    suitabilityCompletedLat:
                      type: string
                    suitabilityCompletedLong:
                      type: string
                    siteSurveyStatus: 
                      type: string
                    siteSurveyCompletedTime:
                      type: string
                    siteSurveyCompletedLat:
                      type: string
                    siteSurveyCompletedLong:
                      type: string
                    profileStatus: 
                      type: string
                    profileCompletedTime:
                      type: string
                    profileCompletedLat:
                      type: string
                    profileCompletedLong:
                      type: string
                    consentStatus: 
                      type: string
                    consentCompletedTime:
                      type: string
                    consentCompletedLat:
                      type: string
                    consentCompletedLong:
                      type: string
                    leadStatus: 
                      type: string
                    leadCompletedTime:
                      type: string
                    leadCompletedLat:
                      type: string
                    leadCompletedLong:
                      type: string
                    consentSignature:
                      type: string
                    appointmentDateTime:
                      type: string
                    suitabilityCriteria:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          id:
                            type: string
                          description:
                            type: string
                          answer:
                            type: string
                          type:
                            type: string
                          qStatus:
                            type: string
                          required:
                            type: string
                          answerTime:
                            type: string
                          answerLat:
                            type: string
                          answerLong:
                            type: string
                          possible_values:
                            type: array
                            items:
                              type: object
                              properties:
                                value:
                                  type: string
                                description:
                                  type: string
                    siteSurvey:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          question:
                            type: string
                          answer:
                            type: string
                          type:
                            type: string
                          lookupList:
                            type: string
                          qStatus:
                            type: string
                          required:
                            type: string

                    roomWifiAnalysis:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: string
                                roomName:
                                  type: string
                                roomStatus:
                                  type: string
                                roomQuestions:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      id:
                                        type: string
                                      question:
                                        type: string
                                      answer:
                                        type: string
                                      type:
                                        type: string
                                      lookupList:
                                        type: string
                                      qStatus:
                                        type: string
                                      required:
                                        type: string           
                                
                    profile:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          categoryName:
                            type: string
                          categoryStatus:
                            type: string
                          categoryType:
                            type: string
                          categoryAddData:
                            type: array
                            items:
                              type: object
                              properties:
                                id: 
                                  type: string
                                catAddName: 
                                  type: string
                                catAddStatus: 
                                  type: string
                                catAddQuestions:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      question: 
                                        type: string
                                      id: 
                                        type: string
                                      answer: 
                                        type: string
                                      type: 
                                        type: string
                                      lookupList: 
                                        type: string
                                      qStatus: 
                                        type: string
                                      required: 
                                        type: string
                          categoryQuestions:
                            type: array
                            items:
                              type: object
                              properties: 
                                id:
                                  type: string
                                question:
                                  type: string
                                answer:
                                  type: string
                                type:
                                  type: string
                                lookupList:
                                  type: string
                                qStatus:
                                  type: string
                                required:
                                  type: string


        default:
          description: server error