swagger: '2.0'
info:
  version: '1.0'
  title: 'Google Identity Toolkit'
  description: ''
schemes:
  - https
host: identitytoolkit.googleapis.com
basePath: /v1

paths:
  /accounts:lookup:
    post:
      summary: get user data
      description: get user data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: key
          description: Web API Key from Firebase Project Console
          type: string
          required: true
          
        - in: body
          name: body
          schema:
            type: object 
            properties:
              idToken:
                type: string
              users:
                type: array
                items:
                  type: object
                  properties:
                    email:
                      type: string
                    localId:
                      type: string
                    emailVerified:
                      type: string
                    passwordUpdatedAt:
                      type: string
                    passwordHash:
                      type: string
                    idToken:
                      type: string
                    refreshToken:
                      type: string
                    expiresIn:
                      type: string
                    displayName:
                      type: string
                    photoUrl:
                      type: string
                    validSince:
                      type: string
                    disabled:
                      type: string
                    lastLoginAt:
                      type: string
                    createdAt:
                      type: string
                    customAuth:
                      type: string

      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              email:
                type: string
              localId:
                type: string
              passwordHash:
                type: string
              idToken:
                type: string
              refreshToken:
                type: string
              expiresIn:
                type: string
              displayName:
                type: string
              photoUrl:
                type: string

        default:
          description: unexpected response
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      properties:
                        message:
                          type: string
                        domain:
                          type: string
                        reason:
                          type: string

  /accounts:update:
    post:
      summary: Update user 
      description: Update user 
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: X-Firebase-Locale
          description: The language code corresponding to the user's locale. Passing this will localize the password reset email sent to the user
          type: string
          required: false
        - in: query
          name: key
          description: Web API Key from Firebase Project Console
          type: string
          required: true
          
        - in: body
          name: body
          schema:
            type: object 
            properties:
              email:
                type: string
              idToken:
                type: string
              returnSecureToken:
                type: string
              password:
                type: string
              displayName:
                type: string
              photoUrl:
                type: string
              deleteAttribute:
                type: string
              oobCode:
                type: string
                description: The action code sent to user's email for email verification eg [VERIFICATION_CODE]

      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              email:
                type: string
              localId:
                type: string
              passwordHash:
                type: string
              idToken:
                type: string
              refreshToken:
                type: string
              expiresIn:
                type: string
              displayName:
                type: string
              photoUrl:
                type: string
              emailVerified:
                type: string

        default:
          description: unexpected response
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      properties:
                        message:
                          type: string
                        domain:
                          type: string
                        reason:
                          type: string

  /accounts:resetPassword:
    post:
      summary: Verify or Confirm password reset code
      description: Verify or Confirm password reset code
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: key
          description: Web API Key from Firebase Project Console
          type: string
          required: true
          
        - in: body
          name: body
          schema:
            type: object 
            properties:
              oobCode:
                type: string
                description: The email action code sent to the user's email for resetting the password.
              newPassword:
                type: string
                description: The user's new password.

 
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              email:
                type: string
              requestType:
                type: string

        default:
          description: unexpected response
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      properties:
                        message:
                          type: string
                        domain:
                          type: string
                        reason:
                          type: string

  /accounts:sendOobCode:
    post:
      summary: Send pword reset or email verification email
      description: Send pword reset or email verification email
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: X-Firebase-Locale
          description: The language code corresponding to the user's locale. Passing this will localize the password reset email sent to the user
          type: string
          required: false
        - in: query
          name: key
          description: Web API Key from Firebase Project Console
          type: string
          required: true
          
        - in: body
          name: body
          schema:
            type: object 
            properties:
              email:
                type: string
              requestType:
                type: string
                description: The kind of OOB code to return. Should be "PASSWORD_RESET" or "VERIFY_EMAIL".
 
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              email:
                type: string

        default:
          description: unexpected response
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      properties:
                        message:
                          type: string
                        domain:
                          type: string
                        reason:
                          type: string

  /accounts:signUp:
    post:
      summary: Sign Up with Email and Password
      description: Sign Up with Email and Password
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: key
          description: Web API Key from Firebase Project Console
          type: string
          required: true
          
        - in: body
          name: body
          schema:
            type: object 
            properties:
              email:
                type: string
              password:
                type: string
              returnSecureToken:
                type: boolean
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              kind:
                type: string
              displayName:
                type: string
              localId:
                type: string
              email:
                type: string
              idToken:
                type: string
              registered:
                type: boolean
              refreshToken:
                type: string
              expiresIn:
                type: string
        default:
          description: SignUp Failed
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      properties:
                        message:
                          type: string
                        domain:
                          type: string
                        reason:
                          type: string

  /accounts:signInWithPassword:
    post:
      summary: Sign In with Email and Password
      description: Verifies the user entered password.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: key
          description: Web API Key from Firebase Project Console
          type: string
          required: true
          
        - in: body
          name: body
          schema:
            type: object 
            properties:
              email:
                type: string
              password:
                type: string
              returnSecureToken:
                type: boolean
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              kind:
                type: string
              displayName:
                type: string
              localId:
                type: string
              email:
                type: string
              idToken:
                type: string
              registered:
                type: boolean
              refreshToken:
                type: string
              expiresIn:
                type: string
        default:
          description: login Failed
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      properties:
                        message:
                          type: string
                        domain:
                          type: string
                        reason:
                          type: string