swagger: '2.0'

info:
  version: '0.1'
  title: Maximo Next Gen API
  description: 'Swagger version of maximo nextgen json/oslc api - without response schemas
                Notes:  basepath can also be /oslc instead of /api'

host: maximo.visualiseinfo.co.uk
basePath: /maximo/api

schemes:
  - https

paths:

  /os/mxsr:     

    post:
      summary: create service request
      description: create service request
      tags: 
        - service requests
      consumes:
        - application/json
      parameters:
        - name: properties
          description: 'You can now use that location URI to fetch the new resource. 
                        Rather than doing a GET to fetch the resource, you may want the response of the create 
                        to contain the new resource. For that, you can add the request header properties. 
                        The properties header follows the syntax of the oslc.select clause. 
                        You can use that to fetch all properties, partial set of properties'
          type: string
          in: header
        - name: maxauth
          description: user password base64 encoded
          type: string
          in: header
        - name: _lid
          description: userid 
          type: string
          in: query
        - name: _lpwd
          description: password
          type: string
          in: query
        - name: lean
          type: integer
          in: query
        - name: Body
          description: Schema will need to be modified to fit fields required
          in: body
          required: true
          schema:
            type: object
            properties: 
              reportedby:
                type: string
              description:
                type: string
      responses:
        201:
          description: Success
        default:
          description: Default Error Response

    get:
      summary: get service requests
      description: query service requests
      tags: 
        - service requests
      parameters:
        - name: maxauth
          description: 'user password base64 encoded'
          type: string
          in: header
        - name: _lid
          description: userid 
          type: string
          in: query
        - name: _lpwd
          description: password
          type: string
          in: query
        - name: lean
          description: '0 or 1 - should normally be set to 1 when set to 1 (true), this will instruct the api to work 
                        with the “lean” JSON format, not the namespaced JSON format that is supported by default.'
          type: integer
          in: query
        - name: oslc.select
          description: 'specifies the set of attributes to fetch from the object structures as well as the related objects.'
          type: string
          in: query
        - name: oslc.properties
          description: 'Properties clause applied to a resource member query following the OSLC query syntax. 
                        Allows for selecting a partial view (limited set of fields) of the member resource'
          type: string
          in: query
        - name: collectioncount
          description: 'You can enable totalCount and totalPages by including the query parameter collectioncount=1'
          type: integer
          in: query
        - name: oslc.pageSize
          description: 'specifies the resources for each page of a query'
          type: integer
          in: query
        - name: oslc.orderBy
          description: 'specifies how the results of a query are ordered'
          type: string
          in: query
        - name: oslc.where
          description: 'specifies the WHERE clause for filtering the result set of a query'
          type: string
          in: query
        - name: opmodeor
          description: 'When set to 1 (true), this will direct the oslc.where clause to use OR rather than AND when 
                        the clause contains multiple conditions'
          type: integer
          in: query
        - name: savedQuery
          type: string
          in: query
        - name: searchAttributes
          description: 'Identifies the resource field(s) to be searched using the values provided in the oslc.searchTerms.
                         Example searchAttributes=description,status. Both parameters must be provided.'
          type: string
          in: query
        - name: oslc.searchTerms
          description: 'Record wide text search for values specified in this query parameter. 
                        Example oslc.searchTerms=”pump”,”broken”. Values are evaluated as an "OR" condition 
                        the field must have a value of either pump or broken, but does not have to have both. 
                        The values provided will be used for searching against the fields identified in 
                        the searchAttributes parameter. Both parameters must be provided.'
          type: string
          in: query
        - name: stablepaging
          description: e.g. stablepaging=true
          type: string
          in: query
        - name: gbcols
          type: string
          in: query
        - name: _dropnulls
          description: 'To force the response to add null value attributes, use the query parameter _dropnulls=0.'
          type: integer
          in: query
        - name: internalvalues
          description: 'To get the internal values use the query parameter internalvalues with the value set to 1.'
          type: integer
          in: query
        - name: attributesearch
          description: 'searched for based on those attribute values. e.g. attributesearch=[SPEED:>=50]'
          type: string
          in: query
      
      responses:
        200:
          description: Success
        default:
          description: Default Error Response

    
    