swagger: '2.0'

info:
  version: "0.1"
  title: 'GraphQL Template for FloPro'
  description: 'GraphQL Template for FloPro'

host: graphqlzero.almansi.me

schemes:
  - https

x-ct-graphql: true

paths:

  /api:
    post:
      summary: Update Single Post
      description: Update Single Post
      tags:
        - 2. Mutation
      consumes:
        - application/json
      produces:
        - application/json  
      parameters:
        - name: token
          in: header
          type: string
        - in: body
          name: body
          description: graphQL Query JSON
          required: true
          schema:
            type: object
            properties:
              query:
                type: string
                default: 'mutation ( $id: ID!, $input: UpdatePostInput!) {
                              updatePost(id: $id, input: $input) {
                                id
                                body
                              }
                            }'
              variables:
                type: object
                properties:
                  id:
                    type: integer  
                  input: 
                    type: object
                    properties:
                      body:
                        type: string

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  updatePost:
                    type: object
                    properties:
                      id:
                        type: string
                      body:
                        type: string
                
        default:
          description: Failed Server Response

  