swagger: "2.0"

info:
  version: "0.2"
  title: "GraphQL Template for Helastel"
  description: "GraphQL Template for Helastel"

host: intelastel.io

schemes:
  - https

x-ct-graphql: true

paths:
  /graphql:
    post:
      summary: Login
      description: Login
      tags:
        - 1. Mutation
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: graphQL Query JSON
          required: true
          schema:
            type: object
            properties:
              query:
                type: string
                default: "mutation($input: LoginInput) {
                  login(input: $input ){
                  data {
                  accessToken
                  refreshToken
                  expiresIn
                  tokenType
                  user {
                  id
                  status
                  }
                  }
                  }
                  }"
              variables:
                type: object
                properties:
                  input:
                    type: object
                    properties:
                      username:
                        type: string
                      password:
                        type: string

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  login:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          accessToken:
                            type: string
                          refreshToken:
                            type: string
                          expiresIn:
                            type: string
                          tokenType:
                            type: string
                          user:
                            type: object
                            properties:
                              id:
                                type: string
                              status:
                                type: string

        default:
          description: Failed Server Response
