swagger: '2.0'
info:
  version: '1.0'
  title: 'cloudinary'
  description: 'cloudinary'
  
host: api.cloudinary.com
basePath: /v1_1/ddniayemy
schemes: 
  - https
  
paths:

  /{resourcetype}/upload:
    post:
      summary: resource upload
      description: resource upload
      tags:
        - upload
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          description: The file to upload
          x-ct-mimetype: image/png
        - in: formData
          name: upload_preset
          type: string
          description: upload preset key
        - in: path
          name: resourcetype
          type: string
          required: true
          description: eg image or video
          
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              url:
                type: string
              secure_url:
                type: string
              original_filename:
                type: string