swagger: "2.0"
info:
  description: Asset Tracking POC 
  version: 1.0.0
  title: Asset Tracking POC 

host: wtfhbndxp3.execute-api.eu-west-2.amazonaws.com
basePath: /development
schemes:
  - https

paths:

  /GetDeviceModels:
    get:
      summary: GetDeviceModels
      description: GetDeviceModels
      tags:
        - Devices
      produces:
        - "application/json"
      parameters:
        - in: header
          name: token
          type: string
          description: bearer token
          required: false
        
      responses:
        200:
          description: "200 response"
          schema:
            type: object
            properties: 
              dataShape: 
                type: object
                properties: 
                  fieldDefinitions: 
                    type: object
                    properties: 
                      DeviceModel: 
                        type: object
                        properties: 
                          name: 
                            type: string
                          description: 
                            type: string
                          baseType: 
                            type: string
                          ordinal: 
                            type: number
                          aspects: 
                            type: object
                            properties: 
                              isPrimaryKey: 
                                type: boolean
                      ModelID: 
                        type: object
                        properties: 
                          name: 
                            type: string
                          description: 
                            type: string
                          baseType: 
                            type: string
                          ordinal: 
                            type: number
                          aspects: 
                            type: object
                            properties: 
                              isPrimaryKey: 
                                type: boolean
              rows: 
                type: array
                items: 
                  type: object
                  properties: 
                    DeviceModel: 
                      type: string
                    ModelID: 
                      type: string  

        default:
          description: "error object"
          schema:
            type: object
            properties:
              message:
                type: string
              code:
                type: string

  /GetDeviceAlarms:
    get:
      summary: GetDeviceAlarms
      description: GetDeviceAlarms
      tags:
        - Devices
      produces:
        - "application/json"
      parameters:
        - in: query
          name: NodeID
          type: string
          description: STRING (as per NodeID on GetAssetTree)
          required: true
        - in: query
          name: StartDate
          type: string
          description: STRING Date ISO Format YYYY-MM-DDTHH:MM:SSZ
          required: true
        - in: query
          name: EndDate
          type: string
          description: STRING Date ISO Format YYYY-MM-DDTHH:MM:SSZ
          required: true
        - in: query
          name: SkipClosedAlerts"
          type: boolean
          description: BOOLEAN
          required: false
        - in: query
          name: OldestFirst
          type: boolean
          description: BOOLEAN
          required: false

      responses:
        200:
          description: "200 response"
          schema:
            type: object
            properties:
              count: 
                type: number
              P1Count: 
                type: number
              P2Count: 
                type: number
              P3Count: 
                type: number
              rows:
                type: array
                items:
                  type: object
                  properties: 
                    AcknowledgedBy: 
                      type: string
                    ClosedBy: 
                      type: string
                    Priority: 
                      type: string
                    AcknowledgedAt: 
                      type: number
                    AlarmCounter: 
                      type: number
                    ClosedAt: 
                      type: number
                    DurationOfAlert: 
                      type: number
                    AlertType: 
                      type: string
                    FiredAt: 
                      type: number
                    NodeID: 
                      type: string
                    id: 
                      type: string
                    timestamp: 
                      type: number
                    timestampString: 
                      type: string 
                    FiredAtString: 
                      type: string
                    LastTimeRaisedString: 
                      type: string
                    AcknowledgedAtString: 
                      type: string
                    ClosedAtString: 
                      type: string

        default:
          description: "error object"
          schema:
            type: object
            properties:
              message:
                type: string
              code:
                type: string

  /GetDeviceHistoricData:
    get:
      summary: GetDeviceHistoricData
      description: GetDeviceHistoricData
      tags:
        - Devices
      produces:
        - "application/json"
      parameters:
        - in: query
          name: NodeID
          type: string
          description: STRING (as per NodeID on GetAssetTree)
          required: true
        - in: query
          name: StartDate
          type: string
          description: STRING Date ISO Format YYYY-MM-DDTHH:MM:SSZ
          required: true
        - in: query
          name: EndDate
          type: string
          description: STRING Date ISO Format YYYY-MM-DDTHH:MM:SSZ
          required: false
        - in: query
          name: OldestFirst
          type: boolean
          description: BOOLEAN
          required: false
        - in: query
          name: last7
          type: boolean
          description: last7
          required: false
        - in: query
          name: last24
          type: boolean
          description: last24
          required: false

      responses:
        200:
          description: "200 response"
          schema:
            type: object
            properties:
              count: 
                type: number
              rows:
                type: array
                items:
                  type: object
                  properties: 
                    distance: 
                      type: number
                    GeofenceName: 
                      type: string
                    GeofenceID: 
                      type: string
                    battery: 
                      type: number
                    speed: 
                      type: number
                    temperature: 
                      type: number
                    BatteryVoltage: 
                      type: string
                    CurrentMeasuredTemperature: 
                      type: string
                    gsm_signal_strength: 
                      type: string
                    MessageCounter: 
                      type: number
                    timestamp: 
                      type: number
                    Location: 
                      type: object
                      properties: 
                        latitude: 
                          type: number
                        longitude: 
                          type: number
                        elevation: 
                          type: number
                    latitude: 
                      type: number
                    longitude: 
                      type: number
                    elevation: 
                      type: number
                    detail: 
                      type: string
                    timestampString: 
                      type: string
              latest_distance: 
                type: number
              latest_GeofenceName: 
                type: string
              latest_GeofenceID: 
                type: string
              latest_battery: 
                type: number
              latest_timestamp: 
                type: number
              latest_Location: 
                type: object
                properties: 
                  latitude: 
                    type: number
                  longitude: 
                    type: number
                  elevation: 
                    type: number
              latest_latitude: 
                type: number
              latest_longitude: 
                type: number
              latest_elevation: 
                type: number
              latest_detail: 
                type: string
              latest_timestampString: 
                type: string
              latest_speed: 
                type: number
              latest_temperature: 
                type: string
              latest_gsm_signal_strength: 
                type: string
                  

        default:
          description: "error object"
          schema:
            type: object
            properties:
              message:
                type: string
              code:
                type: string

  /GetAssetTree:
    get:
      summary: Get Asset Tree
      description: Get Asset Tree
      tags:
        - Devices
      produces:
        - "application/json"
      parameters:
        - in: header
          name: Authorization
          description: Bearer token
          type: string

      responses:
        200:
          description: "200 response"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties: 
                    NodeID: 
                      type: string
                    DeviceModel: 
                      type: string
                    NodeName: 
                      type: string
                    NodeType: 
                      type: string
                    ModelID: 
                      type: string
                    children: 
                      type: array
                      items: 
                        type: object
                        properties: 
                          NodeID: 
                            type: string
                          DeviceModel: 
                            type: string
                          NodeName: 
                            type: string
                          NodeType: 
                            type: string
                          ModelID: 
                            type: string
                          children: 
                            type: array
                            items: 
                              type: object
                              properties: 
                                NodeID: 
                                  type: string
                                DeviceModel: 
                                  type: string
                                NodeName: 
                                  type: string
                                NodeType: 
                                  type: string
                                ModelID: 
                                  type: string
                                latitude: 
                                  type: number
                                longitude: 
                                  type: number
                                elevation: 
                                  type: number
                                children: 
                                  type: array
                                  items: 
                                    type: object
                                    properties: 
                                      NodeID: 
                                        type: string
                                      DeviceModel: 
                                        type: string
                                      NodeName: 
                                        type: string
                                      NodeType: 
                                        type: string
                                      ModelID: 
                                        type: string
                                      latitude: 
                                        type: number
                                      longitude: 
                                        type: number
                                      elevation: 
                                        type: number
                                childrenCount: 
                                  type: number
                          childrenCount: 
                            type: number
                    childrenCount: 
                      type: number
              

        default:
          description: "error object"
          schema:
            type: object
            properties:
              message:
                type: string
              code:
                type: string

    