swagger: '2.0'
info:
  version: '1.0'
  title: 'AWS Cognito IDP API Sign Up'
  description: 'AWS Cognito IDP API Sign Up'

host: cognito-idp.eu-west-2.amazonaws.com
basePath: 
schemes: 
  - https
  
paths:

  /:
    post:
      summary: Sign Up
      description: Sign Up
      produces:
        - application/json
      consumes:
        - application/x-amz-json-1.1
      
      parameters:
        - in: header
          name: X-Amz-Target
          type: string
          description: use - AWSCognitoIdentityProviderService.SignUp
          required: true
        - name: Body
          in: body
          required: true
          schema:
            type: object
            properties: 
              Username:
                type: string
              Password:
                type: string
              ClientId:
                type: string
        
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              CodeDeliveryDetails:
                type: object
                properties: 
                  AttributeName:
                    type: string
                  DeliveryMedium:
                    type: string
                  Destination:
                    type: string
              UserConfirmed:
                type: string
              UserSub:
                type: string

        default:
          description: server error

 