swagger: '2.0'
info:
  version: "0.1"
  title: 'Seat Geek API'
  description: 'Seat Geek API'

host: api.seatgeek.com
basePath: /2

schemes:
  - https
securityDefinitions:
  basicAuth:
    type: basic

# To apply Basic auth to the whole API:
security:
  - basicAuth: []

paths:
  /events:
    get:
      summary: Get All Events
      description: Get All Events
      tags:
        - 1. Events
      consumes:
        - application/json
      parameters:
        - in: query
          name: client_id
          type: string
          description: client id
        - in: query
          name: client_secret
          type: string
          description: client secret
          
        

      responses:
        200:
          description: success response
          schema:
            type: object
            properties:
              events:
                type: array
                items:
                  type: object
                  properties:                   
                    is_open:
                      type: boolean
                    id:
                      type: number
                    stats:
                      type: object
                      properties:
                        visible_listing_count:
                          type: number                       
                        average_price:
                          type: number
                        lowest_sg_base_price_good_deals: 
                          type: string
                        lowest_price_good_deals: 
                          type: string
                        median_price:
                          type: number
                        listing_count:
                          type: number
                        variants: 
                          type: string
                        lowest_price:
                          type: number
                        lowest_sg_base_price:
                          type: number
                        highest_price:
                          type: number
                    title:
                      type: string
                    announce_date:
                      type: string
                    score:
                      type: number
                    access_method:
                      type: string
                    announcements:
                      type: object
                      properties:
                        checkout_disclosures:
                          type: object
                          properties:
                            messages:
                              type: array
                              items:
                                type: object
                                properties:
                                  text:
                                    type: string