swagger: '2.0'
info:
  description: Demo Mock
  version: 1.0.0
  title: Demo Mock

host: virtserver.swaggerhub.com
basePath: /CothamTechnologies/DemoMock1/1.0.0
schemes:
 - https

paths:
  
  /generalData:
    get:
      summary: generalData
      description: generalData
      tags:
        - General
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              attr1:
                type: string

              attr2:
                type: string

              attr3:
                type: string

              attr4:
                type: string

        default:
          description: server error
  
  /fueltypes:
    get:
      summary: Get Fuel Types
      description: Get Fuel Types
      tags:
        - Crowe Mackay
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                description: 
                  type: string
                              


        default:
          description: server error
  

  
  /vehiclemetadata:
    get:
      summary: get vehicle meta data
      description: get vehicle makes - models 
      tags:
        - Crowe Mackay
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                makeName: 
                  type: string
                model:
                  type: array
                  items:
                    type: object
                    properties:
                      modelName:
                        type: string
            example:
              - makeName: Audi
                model:
                  - modelName: model 1
                  - modelName: model 2
                  - modelName: model 3
              - makeName: Jaguar
                model:
                  - modelName: model 1
                  - modelName: model 2
                  - modelName: model 3
              - makeName: Porche
                model:
                  - modelName: model 1
                  - modelName: model 2
                  - modelName: model 3
              - makeName: VW
                model:
                  - modelName: model 1
                  - modelName: model 2
                  - modelName: model 3
              - makeName: Ford
                model:
                  - modelName: model 1
                  - modelName: model 2
                  - modelName: model 3
              - makeName: Honda
                model:
                  - modelName: model 1
                  - modelName: model 2
                  - modelName: model 3


        default:
          description: server error
  
  /fuelprices:
    get:
      summary: Get fuel prices
      description: Get fuel prices
      tags:
        - Crowe Mackay
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                fueltype:
                  type: string
                price:
                  type: string


        default:
          description: server error
  
  /tankvehicle:
    get:
      summary: get tank vehicle list
      description: get tank vehicle list
      tags:
        - Crowe Mackay
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                vehicletank:
                  type: string


        default:
          description: server error
  
 
  /salutations:
    get:
      summary: salutations
      description: salutations
      tags:
        - General
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string


        default:
          description: server error
  
  /addresstype:
    get:
      summary: addresstype
      description: addresstype
      tags:
        - General
      produces:
      - application/json
      parameters:
      - in: query
        name: token
        type: string
        description: token
        required: false
     
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string




        default:
          description: server error
  
  /login:
    get:
      summary: login
      description: login
      tags:
        - General
      produces:
      - application/json
      parameters:
      - in: query
        name: email
        type: string
        description: email
        required: true
      - in: query
        name: password
        type: string
        description: password
        required: true 
     
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
              expiry:
                type: string

        default:
          description: server error