swagger: '2.0'
info:
  version: v1
  title: api.getaddres.io
  description: A simple API for finding postal addresses
  
host: api.getaddress.io
basePath:

schemes:
  - https
  
paths:
  /find/{postcode}:
    get:
      summary: find address from postcode
      description: find address from postcode
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: postcode
          type: string
          required: true
        - in: query
          name: api-key
          type: string
        - in: query
          name: expand
          type: string
        - in: query
          name: format
          type: boolean
        - in: query
          name: sort
          type: boolean
        - in: query
          name: fuzzy
          type: boolean
      responses:
        200:
          description: Returns postal addresses
          schema:
            type: object
            properties:
              postcode: 
                type: string
              latitude: 
                type: number
              longitude: 
                type: number
              addresses: 
                type: array
                items: 
                  type: object
                  properties: 
                    formatted_address: 
                      type: array
                      items: 
                        type: string
                    thoroughfare: 
                      type: string
                    building_name: 
                      type: string
                    sub_building_name: 
                      type: string
                    sub_building_number: 
                      type: string
                    building_number: 
                      type: string
                    line_1: 
                      type: string
                    line_2: 
                      type: string
                    line_3: 
                      type: string
                    line_4: 
                      type: string
                    locality: 
                      type: string
                    town_or_city: 
                      type: string
                    county: 
                      type: string
                    district: 
                      type: string
                    country: 
                      type: string

        default:
          description: Error
       
  